(* ::Package:: *)

rxn = Toolbox`reaction["GAPD", {Toolbox`metabolite["g3p", "c"], Toolbox`metabolite["nad", "c"], Toolbox`metabolite["pi", "c"]}, {Toolbox`metabolite["13dpg", "c"], Toolbox`metabolite["h", "c"], Toolbox`metabolite["nadh", "c"]}, {1, 1, 1, 1, 1, 1}, True];
rNonModelMets[metList_]:=Delete[Delete[metList,Position[metList,MASSToolbox`metabolite["h", "c"]]],Position[metList,MASSToolbox`metabolite["h2o", "c"]]];
metSatForSub=#->\[Infinity]&/@rNonModelMets[getSubstrates[rxn]];
metSatRevSub=#->\[Infinity]&/@rNonModelMets[getProducts[rxn]];
metsFull = {Toolbox`metabolite["13dpg", "c"],Toolbox`metabolite["g3p", "c"],Toolbox`metabolite["nad", "c"],Toolbox`metabolite["nadh", "c"],Toolbox`metabolite["pi", "c"]};
logStepSize=0.2;
nonKmParamWeight=Length[Table[1,{i,minPsDataVal[1],maxPsDataVal[1],logStepSize}]];
eTotal=1;
assumedSaturatingConc=0.01 ;
activeIsoSub=Thread[metsFull->metsFull];

metsFull = {Toolbox`metabolite["13dpg", "c"],Toolbox`metabolite["g3p", "c"],Toolbox`metabolite["nad", "c"],Toolbox`metabolite["nadh", "c"],Toolbox`metabolite["pi", "c"]};
metsSub = {Toolbox`Keq["GAPD"]->"d<0>",Toolbox`metabolite["13dpg", "c"]->"d<1>",Toolbox`metabolite["g3p", "c"]->"d<2>",Toolbox`metabolite["nad", "c"]->"d<3>",Toolbox`metabolite["nadh", "c"]->"d<4>",Toolbox`metabolite["pi", "c"]->"d<5>",Toolbox`parameter["E_total"]->"d<6>",Toolbox`parameter["pH"]->"d<7>",Toolbox`parameter["Temp"]->"d<8>"};
rateConstsSub = {Toolbox`rateconst["GAPD1", False]->"x<0>",Toolbox`rateconst["GAPD1", True]->"x<1>",Toolbox`rateconst["GAPD2", False]->"x<2>",Toolbox`rateconst["GAPD2", True]->"x<3>",Toolbox`rateconst["GAPD3", False]->"x<4>",Toolbox`rateconst["GAPD3", True]->"x<5>",Toolbox`rateconst["GAPD4", False]->"x<6>",Toolbox`rateconst["GAPD4", True]->"x<7>",Toolbox`rateconst["GAPD5", False]->"x<8>",Toolbox`rateconst["GAPD5", True]->"x<9>",Toolbox`rateconst["GAPD6", False]->"x<10>",Toolbox`rateconst["GAPD6", True]->"x<11>"};

bufferInfoDataPath = "test_files/simulate_data/buffer_info.xls";
ionChargeDataPath = "test_files/simulate_data/ion_charge.xls";

bufferInfo = getBufferInfoData[bufferInfoDataPath];
ionCharge = getIonData[ionChargeDataPath];



kmList = {{"nad",0.000044999999999999996`,{{"pi",0.053`},{"g3p",0.089`}},"M",8.9`,22.`,{{"teoa",0.04`}},{}},
		  {"g3p",0.0008900000000000001`,{{"nad",0.0045`},{"pi",0.053`}},"M",8.9`,22.`,{{"teoa",0.04`}},{}},
		  {"pi",0.0005300000000000001`,{{"nad",0.0045`},{"g3p",0.089`}},"M",8.9`,22.`,{{"teoa",0.04`}},{}}};
		  
kcatList = {{{{"g3p",Null},{"nad",Null},{"pi",Null}},268.`,"1/s",8.9`,22.`,{{"teoa",0.04`}},{}}};

KeqVal = 0.408;

otherParmsList = {{"Kd","nad",3.2`*^-7,"M",8.9`,22.`,{{"teoa",0.04`}},{}}};

outputPath = "test_files/simulate_data/";
paramOutputPath = "test_files/simulate_data/";

pHandT={8.9, 22};
KdVal=3.2`*^-7;
KdRatio=Toolbox`rateconst["GAPD1", False]/Toolbox`rateconst["GAPD1", True];

dKdVal =4.25*10^2(*1.92*10^4*);
(*Specify the Equation to Be Used for Fitting*)
dKdRatio =(Toolbox`rateconst["GAPD1", True]Toolbox`rateconst["GAPD2", True]Toolbox`rateconst["GAPD3", True]Toolbox`rateconst["GAPD4", True]Toolbox`rateconst["GAPD5", True])/(Toolbox`rateconst["GAPD1", False]Toolbox`rateconst["GAPD2", False]Toolbox`rateconst["GAPD3", False]Toolbox`rateconst["GAPD4", False]Toolbox`rateconst["GAPD5", False])


KeqName = "GAPD";
allCatalyticReactions = {Toolbox`reaction["GAPD1", {Toolbox`enzyme[{"ID" -> "GAPD", "Compartment" -> "c", "BoundCatalytic" -> {}, "BoundActivators" -> {}, "BoundInhibitors" -> {}, "CatalyticSites" -> DirectedInfinity[1], "ActivationSites" -> 0, "InhibitionSites" -> 0}], Toolbox`metabolite["nad", "c"]}, {Toolbox`enzyme[{"ID" -> "GAPD", "Compartment" -> "c", "BoundCatalytic" -> {Toolbox`Private`wrap[Toolbox`metabolite]["nad", "c"]}, "BoundActivators" -> {}, "BoundInhibitors" -> {}, "CatalyticSites" -> DirectedInfinity[1], "ActivationSites" -> 0, "InhibitionSites" -> 0}]}, {1, 1, 1}, True],Toolbox`reaction["GAPD2", {Toolbox`enzyme[{"ID" -> "GAPD", "Compartment" -> "c", "BoundCatalytic" -> {Toolbox`Private`wrap[Toolbox`metabolite]["13dpg", "c"]}, "BoundActivators" -> {}, "BoundInhibitors" -> {}, "CatalyticSites" -> DirectedInfinity[1], "ActivationSites" -> 0, "InhibitionSites" -> 0}]}, {Toolbox`enzyme[{"ID" -> "GAPD", "Compartment" -> "c", "BoundCatalytic" -> {}, "BoundActivators" -> {}, "BoundInhibitors" -> {}, "CatalyticSites" -> DirectedInfinity[1], "ActivationSites" -> 0, "InhibitionSites" -> 0}], Toolbox`metabolite["13dpg", "c"]}, {1, 1, 1}, True],
						Toolbox`reaction["GAPD3", {Toolbox`enzyme[{"ID" -> "GAPD", "Compartment" -> "c", "BoundCatalytic" -> {Toolbox`Private`wrap[Toolbox`metabolite]["nad", "c"]}, "BoundActivators" -> {}, "BoundInhibitors" -> {}, "CatalyticSites" -> DirectedInfinity[1], "ActivationSites" -> 0, "InhibitionSites" -> 0}], Toolbox`metabolite["g3p", "c"]}, {Toolbox`enzyme[{"ID" -> "GAPD", "Compartment" -> "c", "BoundCatalytic" -> {Toolbox`Private`wrap[Toolbox`metabolite]["nad", "c"], Toolbox`Private`wrap[Toolbox`metabolite]["g3p", "c"]}, "BoundActivators" -> {}, "BoundInhibitors" -> {}, "CatalyticSites" -> DirectedInfinity[1], "ActivationSites" -> 0, "InhibitionSites" -> 0}]}, {1, 1, 1}, True],Toolbox`reaction["GAPD4", {Toolbox`enzyme[{"ID" -> "GAPD", "Compartment" -> "c", "BoundCatalytic" -> {Toolbox`Private`wrap[Toolbox`metabolite]["13dpg", "c"], Toolbox`Private`wrap[Toolbox`metabolite]["nadh", "c"]}, "BoundActivators" -> {}, "BoundInhibitors" -> {}, "CatalyticSites" -> DirectedInfinity[1], "ActivationSites" -> 0, "InhibitionSites" -> 0}]}, {Toolbox`enzyme[{"ID" -> "GAPD", "Compartment" -> "c", "BoundCatalytic" -> {Toolbox`Private`wrap[Toolbox`metabolite]["13dpg", "c"]}, "BoundActivators" -> {}, "BoundInhibitors" -> {}, "CatalyticSites" -> DirectedInfinity[1], "ActivationSites" -> 0, "InhibitionSites" -> 0}], Toolbox`metabolite["nadh", "c"]}, {1, 1, 1}, True],
						Toolbox`reaction["GAPD5", {Toolbox`enzyme[{"ID" -> "GAPD", "Compartment" -> "c", "BoundCatalytic" -> {Toolbox`Private`wrap[Toolbox`metabolite]["nad", "c"], Toolbox`Private`wrap[Toolbox`metabolite]["g3p", "c"]}, "BoundActivators" -> {}, "BoundInhibitors" -> {}, "CatalyticSites" -> DirectedInfinity[1], "ActivationSites" -> 0, "InhibitionSites" -> 0}], Toolbox`metabolite["pi", "c"]}, {Toolbox`enzyme[{"ID" -> "GAPD", "Compartment" -> "c", "BoundCatalytic" -> {Toolbox`Private`wrap[Toolbox`metabolite]["nad", "c"], Toolbox`Private`wrap[Toolbox`metabolite]["g3p", "c"], Toolbox`Private`wrap[Toolbox`metabolite]["pi", "c"]}, "BoundActivators" -> {}, "BoundInhibitors" -> {}, "CatalyticSites" -> DirectedInfinity[1], "ActivationSites" -> 0, "InhibitionSites" -> 0}]}, {1, 1, 1}, True],Toolbox`reaction["GAPD6", {Toolbox`enzyme[{"ID" -> "GAPD", "Compartment" -> "c", "BoundCatalytic" -> {Toolbox`Private`wrap[Toolbox`metabolite]["nad", "c"], Toolbox`Private`wrap[Toolbox`metabolite]["g3p", "c"], Toolbox`Private`wrap[Toolbox`metabolite]["pi", "c"]}, "BoundActivators" -> {}, "BoundInhibitors" -> {}, "CatalyticSites" -> DirectedInfinity[1], "ActivationSites" -> 0, "InhibitionSites" -> 0}]}, {Toolbox`enzyme[{"ID" -> "GAPD", "Compartment" -> "c", "BoundCatalytic" -> {Toolbox`Private`wrap[Toolbox`metabolite]["13dpg", "c"], Toolbox`Private`wrap[Toolbox`metabolite]["nadh", "c"]}, "BoundActivators" -> {}, "BoundInhibitors" -> {}, "CatalyticSites" -> DirectedInfinity[1], "ActivationSites" -> 0, "InhibitionSites" -> 0}]}, {1, 1}, True]};
						
unifiedRateConstList = {Toolbox`rateconst["GAPD1", True]->Toolbox`rateconst["GAPD1", True],Toolbox`rateconst["GAPD1", False]->Toolbox`rateconst["GAPD1", False],Toolbox`rateconst["GAPD2", True]->Toolbox`rateconst["GAPD2", True],Toolbox`rateconst["GAPD2", False]->Toolbox`rateconst["GAPD2", False],Toolbox`rateconst["GAPD3", True]->Toolbox`rateconst["GAPD3", True],Toolbox`rateconst["GAPD3", False]->Toolbox`rateconst["GAPD3", False],Toolbox`rateconst["GAPD4", True]->Toolbox`rateconst["GAPD4", True],Toolbox`rateconst["GAPD4", False]->Toolbox`rateconst["GAPD4", False],Toolbox`rateconst["GAPD5", True]->Toolbox`rateconst["GAPD5", True],Toolbox`rateconst["GAPD5", False]->Toolbox`rateconst["GAPD5", False],Toolbox`rateconst["GAPD6", True]->Toolbox`rateconst["GAPD6", True],Toolbox`rateconst["GAPD6", False]->Toolbox`rateconst["GAPD6", False]};

haldane=haldaneRelation[KeqName,allCatalyticReactions]/.unifiedRateConstList;
haldaneRatio=haldane[[2]]


fileList={"test_files/simulate_data/absRateFor.txt",
		  "test_files/simulate_data/absRateRev.txt",
		  "test_files/simulate_data/relRateFor_g3p.txt",
		  "test_files/simulate_data/relRateFor_nad.txt",
		  "test_files/simulate_data/relRateFor_pi.txt",
		  "test_files/simulate_data/relRateRev_13dpg.txt",
		  "test_files/simulate_data/relRateRev_nadh.txt"};

fileListSub = {"test_files/simulate_data/absRateFor.txt"->(Toolbox`metabolite["g3p", "c"] Toolbox`metabolite["nad", "c"] Toolbox`metabolite["pi", "c"] Toolbox`parameter["E_total"] Toolbox`rateconst["GAPD1", True] Toolbox`rateconst["GAPD2", True] Toolbox`rateconst["GAPD3", True] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True])/(Toolbox`metabolite["g3p", "c"] Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD2", True] Toolbox`rateconst["GAPD3", True] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD1", False] Toolbox`rateconst["GAPD2", True] (Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", True])))+Toolbox`metabolite["nad", "c"] Toolbox`rateconst["GAPD1", True] (Toolbox`metabolite["g3p", "c"] Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD3", True] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD2", True] (Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", True]))+Toolbox`metabolite["g3p", "c"] Toolbox`rateconst["GAPD3", True] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD5", True]+Toolbox`rateconst["GAPD6", True])+Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD5", True] (Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD6", True]))))),
			   "test_files/simulate_data/absRateRev.txt"->(Toolbox`metabolite["13dpg", "c"] Toolbox`metabolite["nadh", "c"] Toolbox`parameter["E_total"] Toolbox`rateconst["GAPD1", False] Toolbox`rateconst["GAPD2", False] Toolbox`rateconst["GAPD3", False] Toolbox`rateconst["GAPD4", False] Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False])/(Toolbox`rateconst["GAPD1", False] Toolbox`rateconst["GAPD3", False] (Toolbox`metabolite["nadh", "c"] Toolbox`rateconst["GAPD4", False] Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD2", True] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", True])))+Toolbox`metabolite["13dpg", "c"] Toolbox`rateconst["GAPD2", False] (Toolbox`rateconst["GAPD1", False] Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", True]))+Toolbox`metabolite["nadh", "c"] Toolbox`rateconst["GAPD4", False] (Toolbox`rateconst["GAPD3", False] Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD1", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD6", True]))))),
			   "test_files/simulate_data/relRateFor_g3p.txt"->(Toolbox`metabolite["g3p", "c"] Toolbox`rateconst["GAPD3", True] (Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD2", True] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`metabolite["nad", "c"] Toolbox`rateconst["GAPD1", True] (Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD2", True] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD5", True]+Toolbox`rateconst["GAPD6", True])+Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD5", True] (Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD6", True])))))/(Toolbox`metabolite["g3p", "c"] Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD2", True] Toolbox`rateconst["GAPD3", True] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD1", False] Toolbox`rateconst["GAPD2", True] (Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", True])))+Toolbox`metabolite["nad", "c"] Toolbox`rateconst["GAPD1", True] (Toolbox`metabolite["g3p", "c"] Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD3", True] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD2", True] (Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", True]))+Toolbox`metabolite["g3p", "c"] Toolbox`rateconst["GAPD3", True] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD5", True]+Toolbox`rateconst["GAPD6", True])+Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD5", True] (Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD6", True]))))),
			   "test_files/simulate_data/relRateFor_nad.txt"->(Toolbox`metabolite["nad", "c"] Toolbox`rateconst["GAPD1", True] (Toolbox`metabolite["g3p", "c"] Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD3", True] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD2", True] (Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", True]))+Toolbox`metabolite["g3p", "c"] Toolbox`rateconst["GAPD3", True] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD5", True]+Toolbox`rateconst["GAPD6", True])+Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD5", True] (Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD6", True])))))/(Toolbox`metabolite["g3p", "c"] Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD2", True] Toolbox`rateconst["GAPD3", True] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD1", False] Toolbox`rateconst["GAPD2", True] (Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", True])))+Toolbox`metabolite["nad", "c"] Toolbox`rateconst["GAPD1", True] (Toolbox`metabolite["g3p", "c"] Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD3", True] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD2", True] (Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", True]))+Toolbox`metabolite["g3p", "c"] Toolbox`rateconst["GAPD3", True] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD5", True]+Toolbox`rateconst["GAPD6", True])+Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD5", True] (Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD6", True]))))),
			   "test_files/simulate_data/relRateFor_pi.txt"->(Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD5", True] ((Toolbox`rateconst["GAPD1", False]+Toolbox`metabolite["nad", "c"] Toolbox`rateconst["GAPD1", True]) Toolbox`rateconst["GAPD2", True] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD6", True]+Toolbox`metabolite["g3p", "c"] Toolbox`rateconst["GAPD3", True] (Toolbox`rateconst["GAPD2", True] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD6", True]+Toolbox`metabolite["nad", "c"] Toolbox`rateconst["GAPD1", True] (Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD2", True] (Toolbox`rateconst["GAPD4", True]+Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD6", True])))))/(Toolbox`metabolite["g3p", "c"] Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD2", True] Toolbox`rateconst["GAPD3", True] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD1", False] Toolbox`rateconst["GAPD2", True] (Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", True])))+Toolbox`metabolite["nad", "c"] Toolbox`rateconst["GAPD1", True] (Toolbox`metabolite["g3p", "c"] Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD3", True] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD2", True] (Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", True]))+Toolbox`metabolite["g3p", "c"] Toolbox`rateconst["GAPD3", True] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD5", True]+Toolbox`rateconst["GAPD6", True])+Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD5", True] (Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD6", True]))))),
			   "test_files/simulate_data/relRateRev_13dpg.txt"->(Toolbox`metabolite["13dpg", "c"] Toolbox`rateconst["GAPD2", False] (Toolbox`rateconst["GAPD1", False] Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", True]))+Toolbox`metabolite["nadh", "c"] Toolbox`rateconst["GAPD4", False] (Toolbox`rateconst["GAPD3", False] Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD1", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD6", True])))))/(Toolbox`rateconst["GAPD1", False] Toolbox`rateconst["GAPD3", False] (Toolbox`metabolite["nadh", "c"] Toolbox`rateconst["GAPD4", False] Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD2", True] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", True])))+Toolbox`metabolite["13dpg", "c"] Toolbox`rateconst["GAPD2", False] (Toolbox`rateconst["GAPD1", False] Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", True]))+Toolbox`metabolite["nadh", "c"] Toolbox`rateconst["GAPD4", False] (Toolbox`rateconst["GAPD3", False] Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD1", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD6", True]))))),
			   "test_files/simulate_data/relRateRev_nadh.txt"->(Toolbox`metabolite["nadh", "c"] Toolbox`rateconst["GAPD4", False] (Toolbox`rateconst["GAPD1", False] Toolbox`rateconst["GAPD3", False] Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`metabolite["13dpg", "c"] Toolbox`rateconst["GAPD2", False] (Toolbox`rateconst["GAPD3", False] Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD1", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD6", True])))))/(Toolbox`rateconst["GAPD1", False] Toolbox`rateconst["GAPD3", False] (Toolbox`metabolite["nadh", "c"] Toolbox`rateconst["GAPD4", False] Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD2", True] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", True])))+Toolbox`metabolite["13dpg", "c"] Toolbox`rateconst["GAPD2", False] (Toolbox`rateconst["GAPD1", False] Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", True]))+Toolbox`metabolite["nadh", "c"] Toolbox`rateconst["GAPD4", False] (Toolbox`rateconst["GAPD3", False] Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD1", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD6", True])))))};

eqnNameList = {"absRateFor","absRateRev","relRateFor_g3p","relRateFor_nad","relRateFor_pi","relRateRev_13dpg","relRateRev_nadh"};

eqnValList = {(Toolbox`metabolite["g3p", "c"] Toolbox`metabolite["nad", "c"] Toolbox`metabolite["pi", "c"] Toolbox`parameter["E_total"] Toolbox`rateconst["GAPD1", True] Toolbox`rateconst["GAPD2", True] Toolbox`rateconst["GAPD3", True] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True])/(Toolbox`metabolite["g3p", "c"] Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD2", True] Toolbox`rateconst["GAPD3", True] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD1", False] Toolbox`rateconst["GAPD2", True] (Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", True])))+Toolbox`metabolite["nad", "c"] Toolbox`rateconst["GAPD1", True] (Toolbox`metabolite["g3p", "c"] Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD3", True] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD2", True] (Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", True]))+Toolbox`metabolite["g3p", "c"] Toolbox`rateconst["GAPD3", True] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD5", True]+Toolbox`rateconst["GAPD6", True])+Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD5", True] (Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD6", True]))))),
			  (Toolbox`metabolite["13dpg", "c"] Toolbox`metabolite["nadh", "c"] Toolbox`parameter["E_total"] Toolbox`rateconst["GAPD1", False] Toolbox`rateconst["GAPD2", False] Toolbox`rateconst["GAPD3", False] Toolbox`rateconst["GAPD4", False] Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False])/(Toolbox`rateconst["GAPD1", False] Toolbox`rateconst["GAPD3", False] (Toolbox`metabolite["nadh", "c"] Toolbox`rateconst["GAPD4", False] Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD2", True] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", True])))+Toolbox`metabolite["13dpg", "c"] Toolbox`rateconst["GAPD2", False] (Toolbox`rateconst["GAPD1", False] Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", True]))+Toolbox`metabolite["nadh", "c"] Toolbox`rateconst["GAPD4", False] (Toolbox`rateconst["GAPD3", False] Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD1", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD6", True]))))),
			  (Toolbox`metabolite["g3p", "c"] Toolbox`rateconst["GAPD3", True] (Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD2", True] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`metabolite["nad", "c"] Toolbox`rateconst["GAPD1", True] (Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD2", True] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD5", True]+Toolbox`rateconst["GAPD6", True])+Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD5", True] (Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD6", True])))))/(Toolbox`metabolite["g3p", "c"] Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD2", True] Toolbox`rateconst["GAPD3", True] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD1", False] Toolbox`rateconst["GAPD2", True] (Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", True])))+Toolbox`metabolite["nad", "c"] Toolbox`rateconst["GAPD1", True] (Toolbox`metabolite["g3p", "c"] Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD3", True] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD2", True] (Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", True]))+Toolbox`metabolite["g3p", "c"] Toolbox`rateconst["GAPD3", True] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD5", True]+Toolbox`rateconst["GAPD6", True])+Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD5", True] (Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD6", True]))))),
			  (Toolbox`metabolite["nad", "c"] Toolbox`rateconst["GAPD1", True] (Toolbox`metabolite["g3p", "c"] Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD3", True] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD2", True] (Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", True]))+Toolbox`metabolite["g3p", "c"] Toolbox`rateconst["GAPD3", True] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD5", True]+Toolbox`rateconst["GAPD6", True])+Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD5", True] (Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD6", True])))))/(Toolbox`metabolite["g3p", "c"] Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD2", True] Toolbox`rateconst["GAPD3", True] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD1", False] Toolbox`rateconst["GAPD2", True] (Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", True])))+Toolbox`metabolite["nad", "c"] Toolbox`rateconst["GAPD1", True] (Toolbox`metabolite["g3p", "c"] Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD3", True] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD2", True] (Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", True]))+Toolbox`metabolite["g3p", "c"] Toolbox`rateconst["GAPD3", True] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD5", True]+Toolbox`rateconst["GAPD6", True])+Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD5", True] (Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD6", True]))))),
		  	(Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD5", True] ((Toolbox`rateconst["GAPD1", False]+Toolbox`metabolite["nad", "c"] Toolbox`rateconst["GAPD1", True]) Toolbox`rateconst["GAPD2", True] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD6", True]+Toolbox`metabolite["g3p", "c"] Toolbox`rateconst["GAPD3", True] (Toolbox`rateconst["GAPD2", True] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD6", True]+Toolbox`metabolite["nad", "c"] Toolbox`rateconst["GAPD1", True] (Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD2", True] (Toolbox`rateconst["GAPD4", True]+Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD6", True])))))/(Toolbox`metabolite["g3p", "c"] Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD2", True] Toolbox`rateconst["GAPD3", True] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD1", False] Toolbox`rateconst["GAPD2", True] (Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", True])))+Toolbox`metabolite["nad", "c"] Toolbox`rateconst["GAPD1", True] (Toolbox`metabolite["g3p", "c"] Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD3", True] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD2", True] (Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", True]))+Toolbox`metabolite["g3p", "c"] Toolbox`rateconst["GAPD3", True] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD5", True]+Toolbox`rateconst["GAPD6", True])+Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD5", True] (Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD6", True]))))),
		  	(Toolbox`metabolite["13dpg", "c"] Toolbox`rateconst["GAPD2", False] (Toolbox`rateconst["GAPD1", False] Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", True]))+Toolbox`metabolite["nadh", "c"] Toolbox`rateconst["GAPD4", False] (Toolbox`rateconst["GAPD3", False] Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD1", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD6", True])))))/(Toolbox`rateconst["GAPD1", False] Toolbox`rateconst["GAPD3", False] (Toolbox`metabolite["nadh", "c"] Toolbox`rateconst["GAPD4", False] Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD2", True] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", True])))+Toolbox`metabolite["13dpg", "c"] Toolbox`rateconst["GAPD2", False] (Toolbox`rateconst["GAPD1", False] Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", True]))+Toolbox`metabolite["nadh", "c"] Toolbox`rateconst["GAPD4", False] (Toolbox`rateconst["GAPD3", False] Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD1", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD6", True]))))),
		  	(Toolbox`metabolite["nadh", "c"] Toolbox`rateconst["GAPD4", False] (Toolbox`rateconst["GAPD1", False] Toolbox`rateconst["GAPD3", False] Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`metabolite["13dpg", "c"] Toolbox`rateconst["GAPD2", False] (Toolbox`rateconst["GAPD3", False] Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD1", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD6", True])))))/(Toolbox`rateconst["GAPD1", False] Toolbox`rateconst["GAPD3", False] (Toolbox`metabolite["nadh", "c"] Toolbox`rateconst["GAPD4", False] Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD2", True] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", True])))+Toolbox`metabolite["13dpg", "c"] Toolbox`rateconst["GAPD2", False] (Toolbox`rateconst["GAPD1", False] Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", True]))+Toolbox`metabolite["nadh", "c"] Toolbox`rateconst["GAPD4", False] (Toolbox`rateconst["GAPD3", False] Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD1", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD6", True])))))}

eqnValListPy = {"(d[2]*d[3]*d[5]*d[6]*x[1]*x[11]*x[3]*x[5]*x[7]*x[9])/(d[2]*d[5]*x[11]*x[3]*x[5]*x[7]*x[9] + x[0]*x[3]*(x[4]*(x[10]*x[8] + x[7]*(x[11] + x[8])) + d[5]*x[11]*x[7]*x[9]) + d[3]*x[1]*(d[2]*d[5]*x[11]*x[5]*x[7]*x[9] + x[3]*(x[4]*(x[10]*x[8] + x[7]*(x[11] + x[8])) + d[5]*x[11]*x[7]*x[9] + d[2]*x[5]*(x[10]*x[8] + d[5]*(x[10] + x[11])*x[9] + x[7]*(x[11] + x[8] + d[5]*x[9])))))",
				"(d[1]*d[4]*d[6]*x[0]*x[10]*x[2]*x[4]*x[6]*x[8])/(x[0]*x[4]*(d[4]*x[10]*x[6]*x[8] + x[3]*(x[10]*x[8] + x[7]*(x[11] + x[8]))) + d[1]*x[2]*(x[0]*x[4]*(x[10]*x[8] + x[7]*(x[11] + x[8])) + d[4]*x[6]*(x[10]*x[4]*x[8] + x[0]*(x[10]*x[8] + x[4]*(x[10] + x[11] + x[8])))))",
				"(d[2]*x[5]*(d[5]*x[11]*x[3]*x[7]*x[9] + d[3]*x[1]*(d[5]*x[11]*x[7]*x[9] + x[3]*(x[10]*x[8] + d[5]*(x[10] + x[11])*x[9] + x[7]*(x[11] + x[8] + d[5]*x[9])))))/(d[2]*d[5]*x[11]*x[3]*x[5]*x[7]*x[9] + x[0]*x[3]*(x[4]*(x[10]*x[8] + x[7]*(x[11] + x[8])) + d[5]*x[11]*x[7]*x[9]) + d[3]*x[1]*(d[2]*d[5]*x[11]*x[5]*x[7]*x[9] + x[3]*(x[4]*(x[10]*x[8] + x[7]*(x[11] + x[8])) + d[5]*x[11]*x[7]*x[9] + d[2]*x[5]*(x[10]*x[8] + d[5]*(x[10] + x[11])*x[9] + x[7]*(x[11] + x[8] + d[5]*x[9])))))",
				"(d[3]*x[1]*(d[2]*d[5]*x[11]*x[5]*x[7]*x[9] + x[3]*(x[4]*(x[10]*x[8] + x[7]*(x[11] + x[8])) + d[5]*x[11]*x[7]*x[9] + d[2]*x[5]*(x[10]*x[8] + d[5]*(x[10] + x[11])*x[9] + x[7]*(x[11] + x[8] + d[5]*x[9])))))/(d[2]*d[5]*x[11]*x[3]*x[5]*x[7]*x[9] + x[0]*x[3]*(x[4]*(x[10]*x[8] + x[7]*(x[11] + x[8])) + d[5]*x[11]*x[7]*x[9]) + d[3]*x[1]*(d[2]*d[5]*x[11]*x[5]*x[7]*x[9] + x[3]*(x[4]*(x[10]*x[8] + x[7]*(x[11] + x[8])) + d[5]*x[11]*x[7]*x[9] + d[2]*x[5]*(x[10]*x[8] + d[5]*(x[10] + x[11])*x[9] + x[7]*(x[11] + x[8] + d[5]*x[9])))))",
				"(d[5]*((x[0] + d[3]*x[1])*x[11]*x[3]*x[7] + d[2]*x[5]*(x[11]*x[3]*x[7] + d[3]*x[1]*(x[11]*x[7] + x[3]*(x[10] + x[11] + x[7]))))*x[9])/(d[2]*d[5]*x[11]*x[3]*x[5]*x[7]*x[9] + x[0]*x[3]*(x[4]*(x[10]*x[8] + x[7]*(x[11] + x[8])) + d[5]*x[11]*x[7]*x[9]) + d[3]*x[1]*(d[2]*d[5]*x[11]*x[5]*x[7]*x[9] + x[3]*(x[4]*(x[10]*x[8] + x[7]*(x[11] + x[8])) + d[5]*x[11]*x[7]*x[9] + d[2]*x[5]*(x[10]*x[8] + d[5]*(x[10] + x[11])*x[9] + x[7]*(x[11] + x[8] + d[5]*x[9])))))",
				"(d[1]*x[2]*(x[0]*x[4]*(x[10]*x[8] + x[7]*(x[11] + x[8])) + d[4]*x[6]*(x[10]*x[4]*x[8] + x[0]*(x[10]*x[8] + x[4]*(x[10] + x[11] + x[8])))))/(x[0]*x[4]*(d[4]*x[10]*x[6]*x[8] + x[3]*(x[10]*x[8] + x[7]*(x[11] + x[8]))) + d[1]*x[2]*(x[0]*x[4]*(x[10]*x[8] + x[7]*(x[11] + x[8])) + d[4]*x[6]*(x[10]*x[4]*x[8] + x[0]*(x[10]*x[8] + x[4]*(x[10] + x[11] + x[8])))))",
				"(d[4]*x[6]*(x[0]*x[10]*x[4]*x[8] + d[1]*x[2]*(x[10]*x[4]*x[8] + x[0]*(x[10]*x[8] + x[4]*(x[10] + x[11] + x[8])))))/(x[0]*x[4]*(d[4]*x[10]*x[6]*x[8] + x[3]*(x[10]*x[8] + x[7]*(x[11] + x[8]))) + d[1]*x[2]*(x[0]*x[4]*(x[10]*x[8] + x[7]*(x[11] + x[8])) + d[4]*x[6]*(x[10]*x[4]*x[8] + x[0]*(x[10]*x[8] + x[4]*(x[10] + x[11] + x[8])))))"}

