(* ::Package:: *)

getInputTestSimulateKmDataGAPD[] := Block[{rxn, metsFull, metSatForSub, metSatRevSub, kmList, otherParmsList, 
	assumedSaturatingConc, eTotal, logStepSize,activeIsoSub, bufferInfo, ionCharge, fileList,
	bufferInfoDataPath, ionChargeDataPath, reverseZeroSub, forwardZeroSub},
	
	rxn = Toolbox`reaction["GAPD", {Toolbox`metabolite["g3p", "c"], Toolbox`metabolite["nad", "c"], Toolbox`metabolite["pi", "c"]}, {Toolbox`metabolite["13dpg", "c"], Toolbox`metabolite["h", "c"], Toolbox`metabolite["nadh", "c"]}, {1, 1, 1, 1, 1, 1}, True];
	{reverseZeroSub, forwardZeroSub, metSatForSub, metSatRevSub} = getMetsSub[rxn];
	metsFull = {Toolbox`metabolite["13dpg", "c"],Toolbox`metabolite["g3p", "c"],Toolbox`metabolite["nad", "c"],Toolbox`metabolite["nadh", "c"],Toolbox`metabolite["pi", "c"]};
	logStepSize=0.2;
	
	eTotal=1;
	assumedSaturatingConc=0.01 ;
	
	activeIsoSub=Thread[metsFull->metsFull];
	
	bufferInfoDataPath = FileNameJoin[{"test_files","simulate_data","buffer_info.csv"}, OperatingSystem->$OperatingSystem];
	ionChargeDataPath = FileNameJoin[{"test_files","simulate_data","ion_charge.csv"}, OperatingSystem->$OperatingSystem];
	bufferInfo = getBufferInfoData[bufferInfoDataPath];
	ionCharge = getIonData[ionChargeDataPath];

	
	kmList = {{"nad",0.000044999999999999996`,{{"pi",0.053`},{"g3p",0.089`}},"M",8.9`,22.`,{{"teoa",0.04`}},{}},
		  {"g3p",0.0008900000000000001`,{{"nad",0.0045`},{"pi",0.053`}},"M",8.9`,22.`,{{"teoa",0.04`}},{}},
		  {"pi",0.0005300000000000001`,{{"nad",0.0045`},{"g3p",0.089`}},"M",8.9`,22.`,{{"teoa",0.04`}},{}}};
	
	otherParmsList = {{"Kd","nad",3.2`*^-7,"M",8.9`,22.`,{{"teoa",0.04`}},{}}};
		  
	fileList={FileNameJoin[{"test_files","simulate_data","absRateFor.txt"}, OperatingSystem->$OperatingSystem],
		 FileNameJoin[{"test_files","simulate_data","absRateRev.txt"}, OperatingSystem->$OperatingSystem],
		 FileNameJoin[{"test_files","simulate_data","relRateFor_g3p.txt"}, OperatingSystem->$OperatingSystem],
		 FileNameJoin[{"test_files","simulate_data","relRateFor_nad.txt"}, OperatingSystem->$OperatingSystem],
		 FileNameJoin[{"test_files","simulate_data","relRateFor_pi.txt"}, OperatingSystem->$OperatingSystem],
		 FileNameJoin[{"test_files","simulate_data","relRateRev_13dpg.txt"}, OperatingSystem->$OperatingSystem],
		 FileNameJoin[{"test_files","simulate_data","relRateRev_nadh.txt"}, OperatingSystem->$OperatingSystem]};

	Return[{rxn, metsFull, metSatForSub, metSatRevSub, kmList, otherParmsList, assumedSaturatingConc, eTotal, 
			logStepSize,activeIsoSub, bufferInfo, ionCharge, fileList}];
];


getInputTestSimulateKmDataTALA2[] := Block[{rxnTALA2, metsFullTALA2, metSatForSubTALA2, metSatRevSubTALA2, kmListTALA2, 
	otherParmsListTALA2, assumedSaturatingConc, eTotal, logStepSize,activeIsoSubTALA2, bufferInfo, ionCharge,  
	fileListTALA2, KeqValTALA2, bufferInfoDataPath, ionChargeDataPath},
	
	logStepSize=0.2;
	eTotal=1;
	assumedSaturatingConc=0.01 ;

	bufferInfoDataPath = FileNameJoin[{"test_files","simulate_data","buffer_info.csv"}, OperatingSystem->$OperatingSystem];
	ionChargeDataPath = FileNameJoin[{"test_files","simulate_data","ion_charge.csv"}, OperatingSystem->$OperatingSystem];

	bufferInfo = getBufferInfoData[bufferInfoDataPath];
	ionCharge = getIonData[ionChargeDataPath];
	
	rxnTALA2 = Toolbox`reaction["TALA2", {Toolbox`metabolite["e4p", "c"], Toolbox`metabolite["f6p", "c"]}, {Toolbox`metabolite["g3p", "c"], Toolbox`metabolite["s7p", "c"]}, {1, 1, 1, 1}, True];
	metsFullTALA2 = {Toolbox`metabolite["e4p", "c"],Toolbox`metabolite["f6p", "c"],Toolbox`metabolite["g3p", "c"],Toolbox`metabolite["s7p", "c"],Toolbox`metabolite["pi", "c"]};
	
	metSatForSubTALA2 = {Toolbox`metabolite["e4p", "c"]->\[Infinity],Toolbox`metabolite["f6p", "c"]->\[Infinity]};
	metSatRevSubTALA2 = {Toolbox`metabolite["g3p", "c"]->\[Infinity],Toolbox`metabolite["s7p", "c"]->\[Infinity]};
	kmListTALA2 = {{"g3p",0.000037999999999999995`,{{"f6p",0.0285`}},"M",8.5`,30.`,{{"glygly",0.05`}},{}},{"e4p",0.00009`,{{"f6p",0.0285`}},"M",8.5`,30.`,{{"glygly",0.05`}},{}},{"r5p",0.031`,{{"f6p",0.0285`}},"M",8.5`,30.`,{{"glygly",0.05`}},{}},{"f6p",0.0012000000000000001`,{{"g3p",0.0038`}},"M",8.5`,30.`,{{"glygly",0.05`}},{}},{"s7p",0.000285`,{{"g3p",0.0038`}},"M",8.5`,30.`,{{"glygly",0.05`}},{}}};
	otherParmsListTALA2 ={};
	fileListTALA2 = {FileNameJoin[{"test_files","simulate_data","absRateFor.txt"}, OperatingSystem->$OperatingSystem],
					FileNameJoin[{"test_files","simulate_data","absRateRev.txt"}, OperatingSystem->$OperatingSystem],
					FileNameJoin[{"test_files","simulate_data","relRateFor_e4p.txt"}, OperatingSystem->$OperatingSystem],
					FileNameJoin[{"test_files","simulate_data","relRateFor_f6p.txt"}, OperatingSystem->$OperatingSystem],
					FileNameJoin[{"test_files","simulate_data","relRateRev_g3p.txt"}, OperatingSystem->$OperatingSystem],
					FileNameJoin[{"test_files","simulate_data","relRateRev_s7p.txt"}, OperatingSystem->$OperatingSystem]};
	KeqValTALA2 = 1/1.19;
	activeIsoSubTALA2 = {Toolbox`metabolite["e4p", "c"]->Toolbox`metabolite["e4p", "c"],Toolbox`metabolite["f6p", "c"]->Toolbox`metabolite["f6p", "c"],Toolbox`metabolite["g3p", "c"]->Toolbox`metabolite["g3p", "c"],Toolbox`metabolite["s7p", "c"]->Toolbox`metabolite["s7p", "c"],Toolbox`metabolite["pi", "c"]->Toolbox`metabolite["pi", "c"]};

	
	Return[{rxnTALA2, metsFullTALA2, metSatForSubTALA2, metSatRevSubTALA2, kmListTALA2, 
	otherParmsListTALA2, assumedSaturatingConc, eTotal, logStepSize, activeIsoSubTALA2,
	bufferInfo, ionCharge, fileListTALA2, KeqValTALA2}];
];


getInputTestSimulateS05DataPFK1[] := Block[{rxn, metsFull, metSatForSub, metSatRevSub, s05List, otherParmsList, 
	assumedSaturatingConc, eTotal, logStepSize,activeIsoSub, bufferInfo, ionCharge, fileList,
	bufferInfoDataPath, ionChargeDataPath, reverseZeroSub, forwardZeroSub},
	
	rxn = Toolbox`reaction["PFK1", {Toolbox`metabolite["atp", "c"], Toolbox`metabolite["f6p", "c"]}, {Toolbox`metabolite["adp", "c"], Toolbox`metabolite["fdp", "c"], Toolbox`metabolite["h", "c"]}, {1, 1, 1, 1, 1}, True];
	{reverseZeroSub, forwardZeroSub, metSatForSub, metSatRevSub} = getMetsSub[rxn];
	metsFull = {Toolbox`metabolite["adp", "c"],Toolbox`metabolite["atp", "c"],Toolbox`metabolite["f6p", "c"],Toolbox`metabolite["fdp", "c"],Toolbox`metabolite["gdp", "c"],Toolbox`metabolite["pep", "c"]};
	logStepSize=0.2;

	eTotal=1;
	assumedSaturatingConc=0.01 ;
	activeIsoSub=Thread[metsFull->metsFull];

	bufferInfoDataPath = FileNameJoin[{"test_files","simulate_data","buffer_info.csv"}, OperatingSystem->$OperatingSystem];
	ionChargeDataPath = FileNameJoin[{"test_files","simulate_data","ion_charge.csv"}, OperatingSystem->$OperatingSystem];

	bufferInfo = getBufferInfoData[bufferInfoDataPath];
	ionCharge = getIonData[ionChargeDataPath];
	
	s05List = {{"f6p",0.00009`,{{"gdp",0.001`},{"atp",0.001`}},"M",8.5`,30.`,{{"detam",0.051`},{"netmphn",0.051`},{"mes",0.1`}},{}}};
	
	otherParmsList = {{"n","",2.11`,"Null",8.5`,30.`,{{"detam",0.051`},{"netmphn",0.051`},{"mes",0.1`}},{}},{"L0","",4.`*^6,"Null",8.5`,28.`,{{"tris",0.05`}},{}}};
		  
	fileList={FileNameJoin[{"test_files","simulate_data","absRateFor.txt"}, OperatingSystem->$OperatingSystem],
				FileNameJoin[{"test_files","simulate_data","absRateRev.txt"}, OperatingSystem->$OperatingSystem],
				FileNameJoin[{"test_files","simulate_data","relRateFor_atp.txt"}, OperatingSystem->$OperatingSystem],
				FileNameJoin[{"test_files","simulate_data","relRateFor_f6p.txt"}, OperatingSystem->$OperatingSystem],
				FileNameJoin[{"test_files","simulate_data","relRateRev_adp.txt"}, OperatingSystem->$OperatingSystem],
				FileNameJoin[{"test_files","simulate_data","relRateRev_fdp.txt"}, OperatingSystem->$OperatingSystem],
				FileNameJoin[{"test_files","simulate_data","prod_inhib_adp.txt"}, OperatingSystem->$OperatingSystem]};

	Return[{rxn, metsFull, metSatForSub, metSatRevSub, s05List, otherParmsList, assumedSaturatingConc, eTotal, 
			logStepSize,activeIsoSub, bufferInfo, ionCharge, fileList}];
];


getInputTestSimulateKcatDataGAPD[] := Block[{rxn, metsFull, metSatForSub, metSatRevSub, kcatList, otherParmsList, 
	assumedSaturatingConc, eTotal, logStepSize,activeIsoSub, bufferInfo, ionCharge, fileList,
	bufferInfoDataPath, ionChargeDataPath, reverseZeroSub, forwardZeroSub, minPsDataVal,maxPsDataVal, nonKmParamWeight},
	

	rxn = Toolbox`reaction["GAPD", {Toolbox`metabolite["g3p", "c"], Toolbox`metabolite["nad", "c"], Toolbox`metabolite["pi", "c"]}, {Toolbox`metabolite["13dpg", "c"], Toolbox`metabolite["h", "c"], Toolbox`metabolite["nadh", "c"]}, {1, 1, 1, 1, 1, 1}, True];
	{reverseZeroSub, forwardZeroSub, metSatForSub, metSatRevSub} = getMetsSub[rxn];
	metsFull = {Toolbox`metabolite["13dpg", "c"],Toolbox`metabolite["g3p", "c"],Toolbox`metabolite["nad", "c"],Toolbox`metabolite["nadh", "c"],Toolbox`metabolite["pi", "c"]};
	logStepSize=0.2;

	eTotal=1;
	assumedSaturatingConc=0.01 ;
	activeIsoSub=Thread[metsFull->metsFull];

	metsFull = {Toolbox`metabolite["13dpg", "c"],Toolbox`metabolite["g3p", "c"],Toolbox`metabolite["nad", "c"],Toolbox`metabolite["nadh", "c"],Toolbox`metabolite["pi", "c"]};
	
	bufferInfoDataPath = FileNameJoin[{"test_files","simulate_data","buffer_info.csv"}, OperatingSystem->$OperatingSystem];
	ionChargeDataPath = FileNameJoin[{"test_files","simulate_data","ion_charge.csv"}, OperatingSystem->$OperatingSystem];

	bufferInfo = getBufferInfoData[bufferInfoDataPath];
	ionCharge = getIonData[ionChargeDataPath];
	
	kcatList = {{{{"g3p",Null},{"nad",Null},{"pi",Null}},268.`,"1/s",8.9`,22.`,{{"teoa",0.04`}},{}}};
	
	otherParmsList = {{"Kd","nad",3.2`*^-7,"M",8.9`,22.`,{{"teoa",0.04`}},{}}};
		  
	fileList={FileNameJoin[{"test_files","simulate_data","absRateFor.txt"}, OperatingSystem->$OperatingSystem],
		  FileNameJoin[{"test_files","simulate_data","absRateRev.txt"}, OperatingSystem->$OperatingSystem],
		  FileNameJoin[{"test_files","simulate_data","relRateFor_g3p.txt"}, OperatingSystem->$OperatingSystem],
		  FileNameJoin[{"test_files","simulate_data","relRateFor_nad.txt"}, OperatingSystem->$OperatingSystem],
		  FileNameJoin[{"test_files","simulate_data","relRateFor_pi.txt"}, OperatingSystem->$OperatingSystem],
		  FileNameJoin[{"test_files","simulate_data","relRateRev_13dpg.txt"}, OperatingSystem->$OperatingSystem],
		  FileNameJoin[{"test_files","simulate_data","relRateRev_nadh.txt"}, OperatingSystem->$OperatingSystem]};
		  
	{minPsDataVal,maxPsDataVal} = getMinMaxPsDataVal[1];
	nonKmParamWeight=Length[Table[1,{i,minPsDataVal,maxPsDataVal,logStepSize}]];

	Return[{rxn, metsFull, metSatForSub, metSatRevSub, kcatList, otherParmsList, assumedSaturatingConc, eTotal, 
			logStepSize,nonKmParamWeight,activeIsoSub, bufferInfo, ionCharge, fileList}];
];


getInputTestSimulateRatiosDataGAPD[] := Block[{rxn, metsFull, rateConstsSub, metsSub, eTotal, logStepSize,nonKmParamWeight,
			fileList, fileListSub, eqnNameList, eqnValList, eqnValListPy,
			minPsDataVal,maxPsDataVal},
	
	rxn = Toolbox`reaction["GAPD", {Toolbox`metabolite["g3p", "c"], Toolbox`metabolite["nad", "c"], Toolbox`metabolite["pi", "c"]}, {Toolbox`metabolite["13dpg", "c"], Toolbox`metabolite["h", "c"], Toolbox`metabolite["nadh", "c"]}, {1, 1, 1, 1, 1, 1}, True];
	metsFull = {Toolbox`metabolite["13dpg", "c"],Toolbox`metabolite["g3p", "c"],Toolbox`metabolite["nad", "c"],Toolbox`metabolite["nadh", "c"],Toolbox`metabolite["pi", "c"]};

	logStepSize=0.2;

	eTotal=1;
	
	metsSub = {Toolbox`Keq["GAPD"]->"d<0>",Toolbox`metabolite["13dpg", "c"]->"d<1>",Toolbox`metabolite["g3p", "c"]->"d<2>",Toolbox`metabolite["nad", "c"]->"d<3>",Toolbox`metabolite["nadh", "c"]->"d<4>",Toolbox`metabolite["pi", "c"]->"d<5>",Toolbox`parameter["GAPD_total"]->"d<6>",Toolbox`parameter["pH"]->"d<7>",Toolbox`parameter["Temp"]->"d<8>"};
	
	rateConstsSub={Toolbox`rateconst["GAPD1", False]->"x<0>",Toolbox`rateconst["GAPD1", True]->"x<1>",Toolbox`rateconst["GAPD2", False]->"x<2>",Toolbox`rateconst["GAPD2", True]->"x<3>",Toolbox`rateconst["GAPD3", False]->"x<4>",Toolbox`rateconst["GAPD3", True]->"x<5>",Toolbox`rateconst["GAPD4", False]->"x<6>",Toolbox`rateconst["GAPD4", True]->"x<7>",Toolbox`rateconst["GAPD5", False]->"x<8>",Toolbox`rateconst["GAPD5", True]->"x<9>",Toolbox`rateconst["GAPD6", False]->"x<10>",Toolbox`rateconst["GAPD6", True]->"x<11>"};
		  
	fileList={FileNameJoin[{"test_files","simulate_data","absRateFor.txt"}, OperatingSystem->$OperatingSystem],
		  FileNameJoin[{"test_files","simulate_data","absRateRev.txt"}, OperatingSystem->$OperatingSystem],
		  FileNameJoin[{"test_files","simulate_data","relRateFor_g3p.txt"}, OperatingSystem->$OperatingSystem],
		  FileNameJoin[{"test_files","simulate_data","relRateFor_nad.txt"}, OperatingSystem->$OperatingSystem],
		  FileNameJoin[{"test_files","simulate_data","relRateFor_pi.txt"}, OperatingSystem->$OperatingSystem],
		  FileNameJoin[{"test_files","simulate_data","relRateRev_13dpg.txt"}, OperatingSystem->$OperatingSystem],
		  FileNameJoin[{"test_files","simulate_data","relRateRev_nadh.txt"}, OperatingSystem->$OperatingSystem]};

	{minPsDataVal,maxPsDataVal} = getMinMaxPsDataVal[1];
	nonKmParamWeight=Length[Table[1,{i,minPsDataVal,maxPsDataVal,logStepSize}]];
	
	fileListSub = {FileNameJoin[{"test_files","simulate_data","absRateFor.txt"}, OperatingSystem->$OperatingSystem]->(Toolbox`metabolite["g3p", "c"] Toolbox`metabolite["nad", "c"] Toolbox`metabolite["pi", "c"] Toolbox`parameter["GAPD_total"] Toolbox`rateconst["GAPD1", True] Toolbox`rateconst["GAPD2", True] Toolbox`rateconst["GAPD3", True] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True])/(Toolbox`metabolite["g3p", "c"] Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD2", True] Toolbox`rateconst["GAPD3", True] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD1", False] Toolbox`rateconst["GAPD2", True] (Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", True])))+Toolbox`metabolite["nad", "c"] Toolbox`rateconst["GAPD1", True] (Toolbox`metabolite["g3p", "c"] Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD3", True] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD2", True] (Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", True]))+Toolbox`metabolite["g3p", "c"] Toolbox`rateconst["GAPD3", True] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD5", True]+Toolbox`rateconst["GAPD6", True])+Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD5", True] (Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD6", True]))))),
			   FileNameJoin[{"test_files","simulate_data","absRateRev.txt"}, OperatingSystem->$OperatingSystem]->(Toolbox`metabolite["13dpg", "c"] Toolbox`metabolite["nadh", "c"] Toolbox`parameter["GAPD_total"] Toolbox`rateconst["GAPD1", False] Toolbox`rateconst["GAPD2", False] Toolbox`rateconst["GAPD3", False] Toolbox`rateconst["GAPD4", False] Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False])/(Toolbox`rateconst["GAPD1", False] Toolbox`rateconst["GAPD3", False] (Toolbox`metabolite["nadh", "c"] Toolbox`rateconst["GAPD4", False] Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD2", True] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", True])))+Toolbox`metabolite["13dpg", "c"] Toolbox`rateconst["GAPD2", False] (Toolbox`rateconst["GAPD1", False] Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", True]))+Toolbox`metabolite["nadh", "c"] Toolbox`rateconst["GAPD4", False] (Toolbox`rateconst["GAPD3", False] Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD1", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD6", True]))))),
			   FileNameJoin[{"test_files","simulate_data","relRateFor_g3p.txt"}, OperatingSystem->$OperatingSystem]->(Toolbox`metabolite["g3p", "c"] Toolbox`rateconst["GAPD3", True] (Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD2", True] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`metabolite["nad", "c"] Toolbox`rateconst["GAPD1", True] (Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD2", True] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD5", True]+Toolbox`rateconst["GAPD6", True])+Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD5", True] (Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD6", True])))))/(Toolbox`metabolite["g3p", "c"] Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD2", True] Toolbox`rateconst["GAPD3", True] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD1", False] Toolbox`rateconst["GAPD2", True] (Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", True])))+Toolbox`metabolite["nad", "c"] Toolbox`rateconst["GAPD1", True] (Toolbox`metabolite["g3p", "c"] Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD3", True] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD2", True] (Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", True]))+Toolbox`metabolite["g3p", "c"] Toolbox`rateconst["GAPD3", True] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD5", True]+Toolbox`rateconst["GAPD6", True])+Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD5", True] (Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD6", True]))))),
			   FileNameJoin[{"test_files","simulate_data","relRateFor_nad.txt"}, OperatingSystem->$OperatingSystem]->(Toolbox`metabolite["nad", "c"] Toolbox`rateconst["GAPD1", True] (Toolbox`metabolite["g3p", "c"] Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD3", True] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD2", True] (Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", True]))+Toolbox`metabolite["g3p", "c"] Toolbox`rateconst["GAPD3", True] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD5", True]+Toolbox`rateconst["GAPD6", True])+Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD5", True] (Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD6", True])))))/(Toolbox`metabolite["g3p", "c"] Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD2", True] Toolbox`rateconst["GAPD3", True] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD1", False] Toolbox`rateconst["GAPD2", True] (Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", True])))+Toolbox`metabolite["nad", "c"] Toolbox`rateconst["GAPD1", True] (Toolbox`metabolite["g3p", "c"] Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD3", True] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD2", True] (Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", True]))+Toolbox`metabolite["g3p", "c"] Toolbox`rateconst["GAPD3", True] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD5", True]+Toolbox`rateconst["GAPD6", True])+Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD5", True] (Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD6", True]))))),
			   FileNameJoin[{"test_files","simulate_data","relRateFor_pi.txt"}, OperatingSystem->$OperatingSystem]->(Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD5", True] ((Toolbox`rateconst["GAPD1", False]+Toolbox`metabolite["nad", "c"] Toolbox`rateconst["GAPD1", True]) Toolbox`rateconst["GAPD2", True] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD6", True]+Toolbox`metabolite["g3p", "c"] Toolbox`rateconst["GAPD3", True] (Toolbox`rateconst["GAPD2", True] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD6", True]+Toolbox`metabolite["nad", "c"] Toolbox`rateconst["GAPD1", True] (Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD2", True] (Toolbox`rateconst["GAPD4", True]+Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD6", True])))))/(Toolbox`metabolite["g3p", "c"] Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD2", True] Toolbox`rateconst["GAPD3", True] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD1", False] Toolbox`rateconst["GAPD2", True] (Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", True])))+Toolbox`metabolite["nad", "c"] Toolbox`rateconst["GAPD1", True] (Toolbox`metabolite["g3p", "c"] Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD3", True] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD2", True] (Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", True]))+Toolbox`metabolite["g3p", "c"] Toolbox`rateconst["GAPD3", True] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD5", True]+Toolbox`rateconst["GAPD6", True])+Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD5", True] (Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD6", True]))))),
			  FileNameJoin[{"test_files","simulate_data","relRateRev_13dpg.txt"}, OperatingSystem->$OperatingSystem]->(Toolbox`metabolite["13dpg", "c"] Toolbox`rateconst["GAPD2", False] (Toolbox`rateconst["GAPD1", False] Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", True]))+Toolbox`metabolite["nadh", "c"] Toolbox`rateconst["GAPD4", False] (Toolbox`rateconst["GAPD3", False] Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD1", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD6", True])))))/(Toolbox`rateconst["GAPD1", False] Toolbox`rateconst["GAPD3", False] (Toolbox`metabolite["nadh", "c"] Toolbox`rateconst["GAPD4", False] Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD2", True] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", True])))+Toolbox`metabolite["13dpg", "c"] Toolbox`rateconst["GAPD2", False] (Toolbox`rateconst["GAPD1", False] Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", True]))+Toolbox`metabolite["nadh", "c"] Toolbox`rateconst["GAPD4", False] (Toolbox`rateconst["GAPD3", False] Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD1", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD6", True]))))),
			   FileNameJoin[{"test_files","simulate_data","relRateRev_nadh.txt"}, OperatingSystem->$OperatingSystem]->(Toolbox`metabolite["nadh", "c"] Toolbox`rateconst["GAPD4", False] (Toolbox`rateconst["GAPD1", False] Toolbox`rateconst["GAPD3", False] Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`metabolite["13dpg", "c"] Toolbox`rateconst["GAPD2", False] (Toolbox`rateconst["GAPD3", False] Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD1", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD6", True])))))/(Toolbox`rateconst["GAPD1", False] Toolbox`rateconst["GAPD3", False] (Toolbox`metabolite["nadh", "c"] Toolbox`rateconst["GAPD4", False] Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD2", True] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", True])))+Toolbox`metabolite["13dpg", "c"] Toolbox`rateconst["GAPD2", False] (Toolbox`rateconst["GAPD1", False] Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", True]))+Toolbox`metabolite["nadh", "c"] Toolbox`rateconst["GAPD4", False] (Toolbox`rateconst["GAPD3", False] Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD1", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD6", True])))))};

	eqnNameList = {"absRateFor","absRateRev","relRateFor_g3p","relRateFor_nad","relRateFor_pi","relRateRev_13dpg","relRateRev_nadh"};

	eqnValList = {(Toolbox`metabolite["g3p", "c"] Toolbox`metabolite["nad", "c"] Toolbox`metabolite["pi", "c"] Toolbox`parameter["GAPD_total"] Toolbox`rateconst["GAPD1", True] Toolbox`rateconst["GAPD2", True] Toolbox`rateconst["GAPD3", True] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True])/(Toolbox`metabolite["g3p", "c"] Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD2", True] Toolbox`rateconst["GAPD3", True] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD1", False] Toolbox`rateconst["GAPD2", True] (Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", True])))+Toolbox`metabolite["nad", "c"] Toolbox`rateconst["GAPD1", True] (Toolbox`metabolite["g3p", "c"] Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD3", True] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD2", True] (Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", True]))+Toolbox`metabolite["g3p", "c"] Toolbox`rateconst["GAPD3", True] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD5", True]+Toolbox`rateconst["GAPD6", True])+Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD5", True] (Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD6", True]))))),
			  (Toolbox`metabolite["13dpg", "c"] Toolbox`metabolite["nadh", "c"] Toolbox`parameter["GAPD_total"] Toolbox`rateconst["GAPD1", False] Toolbox`rateconst["GAPD2", False] Toolbox`rateconst["GAPD3", False] Toolbox`rateconst["GAPD4", False] Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False])/(Toolbox`rateconst["GAPD1", False] Toolbox`rateconst["GAPD3", False] (Toolbox`metabolite["nadh", "c"] Toolbox`rateconst["GAPD4", False] Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD2", True] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", True])))+Toolbox`metabolite["13dpg", "c"] Toolbox`rateconst["GAPD2", False] (Toolbox`rateconst["GAPD1", False] Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", True]))+Toolbox`metabolite["nadh", "c"] Toolbox`rateconst["GAPD4", False] (Toolbox`rateconst["GAPD3", False] Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD1", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD6", True]))))),
			  (Toolbox`metabolite["g3p", "c"] Toolbox`rateconst["GAPD3", True] (Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD2", True] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`metabolite["nad", "c"] Toolbox`rateconst["GAPD1", True] (Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD2", True] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD5", True]+Toolbox`rateconst["GAPD6", True])+Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD5", True] (Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD6", True])))))/(Toolbox`metabolite["g3p", "c"] Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD2", True] Toolbox`rateconst["GAPD3", True] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD1", False] Toolbox`rateconst["GAPD2", True] (Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", True])))+Toolbox`metabolite["nad", "c"] Toolbox`rateconst["GAPD1", True] (Toolbox`metabolite["g3p", "c"] Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD3", True] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD2", True] (Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", True]))+Toolbox`metabolite["g3p", "c"] Toolbox`rateconst["GAPD3", True] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD5", True]+Toolbox`rateconst["GAPD6", True])+Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD5", True] (Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD6", True]))))),
			  (Toolbox`metabolite["nad", "c"] Toolbox`rateconst["GAPD1", True] (Toolbox`metabolite["g3p", "c"] Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD3", True] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD2", True] (Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", True]))+Toolbox`metabolite["g3p", "c"] Toolbox`rateconst["GAPD3", True] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD5", True]+Toolbox`rateconst["GAPD6", True])+Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD5", True] (Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD6", True])))))/(Toolbox`metabolite["g3p", "c"] Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD2", True] Toolbox`rateconst["GAPD3", True] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD1", False] Toolbox`rateconst["GAPD2", True] (Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", True])))+Toolbox`metabolite["nad", "c"] Toolbox`rateconst["GAPD1", True] (Toolbox`metabolite["g3p", "c"] Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD3", True] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD2", True] (Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", True]))+Toolbox`metabolite["g3p", "c"] Toolbox`rateconst["GAPD3", True] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD5", True]+Toolbox`rateconst["GAPD6", True])+Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD5", True] (Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD6", True]))))),
		  	(Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD5", True] ((Toolbox`rateconst["GAPD1", False]+Toolbox`metabolite["nad", "c"] Toolbox`rateconst["GAPD1", True]) Toolbox`rateconst["GAPD2", True] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD6", True]+Toolbox`metabolite["g3p", "c"] Toolbox`rateconst["GAPD3", True] (Toolbox`rateconst["GAPD2", True] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD6", True]+Toolbox`metabolite["nad", "c"] Toolbox`rateconst["GAPD1", True] (Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD2", True] (Toolbox`rateconst["GAPD4", True]+Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD6", True])))))/(Toolbox`metabolite["g3p", "c"] Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD2", True] Toolbox`rateconst["GAPD3", True] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD1", False] Toolbox`rateconst["GAPD2", True] (Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", True])))+Toolbox`metabolite["nad", "c"] Toolbox`rateconst["GAPD1", True] (Toolbox`metabolite["g3p", "c"] Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD3", True] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD2", True] (Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", True]))+Toolbox`metabolite["g3p", "c"] Toolbox`rateconst["GAPD3", True] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD5", True]+Toolbox`rateconst["GAPD6", True])+Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD5", True] (Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD6", True]))))),
		  	(Toolbox`metabolite["13dpg", "c"] Toolbox`rateconst["GAPD2", False] (Toolbox`rateconst["GAPD1", False] Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", True]))+Toolbox`metabolite["nadh", "c"] Toolbox`rateconst["GAPD4", False] (Toolbox`rateconst["GAPD3", False] Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD1", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD6", True])))))/(Toolbox`rateconst["GAPD1", False] Toolbox`rateconst["GAPD3", False] (Toolbox`metabolite["nadh", "c"] Toolbox`rateconst["GAPD4", False] Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD2", True] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", True])))+Toolbox`metabolite["13dpg", "c"] Toolbox`rateconst["GAPD2", False] (Toolbox`rateconst["GAPD1", False] Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", True]))+Toolbox`metabolite["nadh", "c"] Toolbox`rateconst["GAPD4", False] (Toolbox`rateconst["GAPD3", False] Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD1", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD6", True]))))),
		  	(Toolbox`metabolite["nadh", "c"] Toolbox`rateconst["GAPD4", False] (Toolbox`rateconst["GAPD1", False] Toolbox`rateconst["GAPD3", False] Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`metabolite["13dpg", "c"] Toolbox`rateconst["GAPD2", False] (Toolbox`rateconst["GAPD3", False] Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD1", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD6", True])))))/(Toolbox`rateconst["GAPD1", False] Toolbox`rateconst["GAPD3", False] (Toolbox`metabolite["nadh", "c"] Toolbox`rateconst["GAPD4", False] Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD2", True] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", True])))+Toolbox`metabolite["13dpg", "c"] Toolbox`rateconst["GAPD2", False] (Toolbox`rateconst["GAPD1", False] Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", True]))+Toolbox`metabolite["nadh", "c"] Toolbox`rateconst["GAPD4", False] (Toolbox`rateconst["GAPD3", False] Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD1", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD6", True])))))};

	eqnValListPy = {"(d[2]*d[3]*d[5]*d[6]*x[1]*x[11]*x[3]*x[5]*x[7]*x[9])/(d[2]*d[5]*x[11]*x[3]*x[5]*x[7]*x[9] + x[0]*x[3]*(x[4]*(x[10]*x[8] + x[7]*(x[11] + x[8])) + d[5]*x[11]*x[7]*x[9]) + d[3]*x[1]*(d[2]*d[5]*x[11]*x[5]*x[7]*x[9] + x[3]*(x[4]*(x[10]*x[8] + x[7]*(x[11] + x[8])) + d[5]*x[11]*x[7]*x[9] + d[2]*x[5]*(x[10]*x[8] + d[5]*(x[10] + x[11])*x[9] + x[7]*(x[11] + x[8] + d[5]*x[9])))))",
				"(d[1]*d[4]*d[6]*x[0]*x[10]*x[2]*x[4]*x[6]*x[8])/(x[0]*x[4]*(d[4]*x[10]*x[6]*x[8] + x[3]*(x[10]*x[8] + x[7]*(x[11] + x[8]))) + d[1]*x[2]*(x[0]*x[4]*(x[10]*x[8] + x[7]*(x[11] + x[8])) + d[4]*x[6]*(x[10]*x[4]*x[8] + x[0]*(x[10]*x[8] + x[4]*(x[10] + x[11] + x[8])))))",
				"(d[2]*x[5]*(d[5]*x[11]*x[3]*x[7]*x[9] + d[3]*x[1]*(d[5]*x[11]*x[7]*x[9] + x[3]*(x[10]*x[8] + d[5]*(x[10] + x[11])*x[9] + x[7]*(x[11] + x[8] + d[5]*x[9])))))/(d[2]*d[5]*x[11]*x[3]*x[5]*x[7]*x[9] + x[0]*x[3]*(x[4]*(x[10]*x[8] + x[7]*(x[11] + x[8])) + d[5]*x[11]*x[7]*x[9]) + d[3]*x[1]*(d[2]*d[5]*x[11]*x[5]*x[7]*x[9] + x[3]*(x[4]*(x[10]*x[8] + x[7]*(x[11] + x[8])) + d[5]*x[11]*x[7]*x[9] + d[2]*x[5]*(x[10]*x[8] + d[5]*(x[10] + x[11])*x[9] + x[7]*(x[11] + x[8] + d[5]*x[9])))))",
				"(d[3]*x[1]*(d[2]*d[5]*x[11]*x[5]*x[7]*x[9] + x[3]*(x[4]*(x[10]*x[8] + x[7]*(x[11] + x[8])) + d[5]*x[11]*x[7]*x[9] + d[2]*x[5]*(x[10]*x[8] + d[5]*(x[10] + x[11])*x[9] + x[7]*(x[11] + x[8] + d[5]*x[9])))))/(d[2]*d[5]*x[11]*x[3]*x[5]*x[7]*x[9] + x[0]*x[3]*(x[4]*(x[10]*x[8] + x[7]*(x[11] + x[8])) + d[5]*x[11]*x[7]*x[9]) + d[3]*x[1]*(d[2]*d[5]*x[11]*x[5]*x[7]*x[9] + x[3]*(x[4]*(x[10]*x[8] + x[7]*(x[11] + x[8])) + d[5]*x[11]*x[7]*x[9] + d[2]*x[5]*(x[10]*x[8] + d[5]*(x[10] + x[11])*x[9] + x[7]*(x[11] + x[8] + d[5]*x[9])))))",
				"(d[5]*((x[0] + d[3]*x[1])*x[11]*x[3]*x[7] + d[2]*x[5]*(x[11]*x[3]*x[7] + d[3]*x[1]*(x[11]*x[7] + x[3]*(x[10] + x[11] + x[7]))))*x[9])/(d[2]*d[5]*x[11]*x[3]*x[5]*x[7]*x[9] + x[0]*x[3]*(x[4]*(x[10]*x[8] + x[7]*(x[11] + x[8])) + d[5]*x[11]*x[7]*x[9]) + d[3]*x[1]*(d[2]*d[5]*x[11]*x[5]*x[7]*x[9] + x[3]*(x[4]*(x[10]*x[8] + x[7]*(x[11] + x[8])) + d[5]*x[11]*x[7]*x[9] + d[2]*x[5]*(x[10]*x[8] + d[5]*(x[10] + x[11])*x[9] + x[7]*(x[11] + x[8] + d[5]*x[9])))))",
				"(d[1]*x[2]*(x[0]*x[4]*(x[10]*x[8] + x[7]*(x[11] + x[8])) + d[4]*x[6]*(x[10]*x[4]*x[8] + x[0]*(x[10]*x[8] + x[4]*(x[10] + x[11] + x[8])))))/(x[0]*x[4]*(d[4]*x[10]*x[6]*x[8] + x[3]*(x[10]*x[8] + x[7]*(x[11] + x[8]))) + d[1]*x[2]*(x[0]*x[4]*(x[10]*x[8] + x[7]*(x[11] + x[8])) + d[4]*x[6]*(x[10]*x[4]*x[8] + x[0]*(x[10]*x[8] + x[4]*(x[10] + x[11] + x[8])))))",
				"(d[4]*x[6]*(x[0]*x[10]*x[4]*x[8] + d[1]*x[2]*(x[10]*x[4]*x[8] + x[0]*(x[10]*x[8] + x[4]*(x[10] + x[11] + x[8])))))/(x[0]*x[4]*(d[4]*x[10]*x[6]*x[8] + x[3]*(x[10]*x[8] + x[7]*(x[11] + x[8]))) + d[1]*x[2]*(x[0]*x[4]*(x[10]*x[8] + x[7]*(x[11] + x[8])) + d[4]*x[6]*(x[10]*x[4]*x[8] + x[0]*(x[10]*x[8] + x[4]*(x[10] + x[11] + x[8])))))"};



	Return[{rxn, metsFull, rateConstsSub, metsSub, eTotal, logStepSize,nonKmParamWeight,
			fileList, fileListSub, eqnNameList, eqnValList, eqnValListPy}];
];


getInputTestSimulateKeqDataGAPD[] := Block[{rxn, metsFull, rateConstsSub, metsSub, eTotal, logStepSize,nonKmParamWeight,
			fileList, fileListSub, eqnNameList, eqnValList, eqnValListPy,
			minPsDataVal,maxPsDataVal, allCatalyticReactions, unifiedRateConstList},
	
	rxn = Toolbox`reaction["GAPD", {Toolbox`metabolite["g3p", "c"], Toolbox`metabolite["nad", "c"], Toolbox`metabolite["pi", "c"]}, {Toolbox`metabolite["13dpg", "c"], Toolbox`metabolite["h", "c"], Toolbox`metabolite["nadh", "c"]}, {1, 1, 1, 1, 1, 1}, True];
	metsFull = {Toolbox`metabolite["13dpg", "c"],Toolbox`metabolite["g3p", "c"],Toolbox`metabolite["nad", "c"],Toolbox`metabolite["nadh", "c"],Toolbox`metabolite["pi", "c"]};
	logStepSize=0.2;

	eTotal=1;
	
	metsSub = {Toolbox`Keq["GAPD"]->"d<0>",Toolbox`metabolite["13dpg", "c"]->"d<1>",Toolbox`metabolite["g3p", "c"]->"d<2>",Toolbox`metabolite["nad", "c"]->"d<3>",Toolbox`metabolite["nadh", "c"]->"d<4>",Toolbox`metabolite["pi", "c"]->"d<5>",Toolbox`parameter["GAPD_total"]->"d<6>",Toolbox`parameter["pH"]->"d<7>",Toolbox`parameter["Temp"]->"d<8>"};
	
	rateConstsSub={Toolbox`rateconst["GAPD1", False]->"x<0>",Toolbox`rateconst["GAPD1", True]->"x<1>",Toolbox`rateconst["GAPD2", False]->"x<2>",Toolbox`rateconst["GAPD2", True]->"x<3>",Toolbox`rateconst["GAPD3", False]->"x<4>",Toolbox`rateconst["GAPD3", True]->"x<5>",Toolbox`rateconst["GAPD4", False]->"x<6>",Toolbox`rateconst["GAPD4", True]->"x<7>",Toolbox`rateconst["GAPD5", False]->"x<8>",Toolbox`rateconst["GAPD5", True]->"x<9>",Toolbox`rateconst["GAPD6", False]->"x<10>",Toolbox`rateconst["GAPD6", True]->"x<11>"};
		  
	fileList={FileNameJoin[{"test_files","simulate_data","absRateFor.txt"}, OperatingSystem->$OperatingSystem],
		  FileNameJoin[{"test_files","simulate_data","absRateRev.txt"}, OperatingSystem->$OperatingSystem],
		  FileNameJoin[{"test_files","simulate_data","relRateFor_g3p.txt"}, OperatingSystem->$OperatingSystem],
		 FileNameJoin[{"test_files","simulate_data","relRateFor_nad.txt"}, OperatingSystem->$OperatingSystem],
		  FileNameJoin[{"test_files","simulate_data","relRateFor_pi.txt"}, OperatingSystem->$OperatingSystem],
		  FileNameJoin[{"test_files","simulate_data","relRateRev_13dpg.txt"}, OperatingSystem->$OperatingSystem],
		  FileNameJoin[{"test_files","simulate_data","relRateRev_nadh.txt"}, OperatingSystem->$OperatingSystem]};
		  
	{minPsDataVal,maxPsDataVal} = getMinMaxPsDataVal[1];
	nonKmParamWeight=Length[Table[1,{i,minPsDataVal,maxPsDataVal,logStepSize}]];
	
	fileListSub = {FileNameJoin[{"test_files","simulate_data","absRateFor.txt"}, OperatingSystem->$OperatingSystem]->(Toolbox`metabolite["g3p", "c"] Toolbox`metabolite["nad", "c"] Toolbox`metabolite["pi", "c"] Toolbox`parameter["GAPD_total"] Toolbox`rateconst["GAPD1", True] Toolbox`rateconst["GAPD2", True] Toolbox`rateconst["GAPD3", True] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True])/(Toolbox`metabolite["g3p", "c"] Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD2", True] Toolbox`rateconst["GAPD3", True] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD1", False] Toolbox`rateconst["GAPD2", True] (Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", True])))+Toolbox`metabolite["nad", "c"] Toolbox`rateconst["GAPD1", True] (Toolbox`metabolite["g3p", "c"] Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD3", True] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD2", True] (Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", True]))+Toolbox`metabolite["g3p", "c"] Toolbox`rateconst["GAPD3", True] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD5", True]+Toolbox`rateconst["GAPD6", True])+Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD5", True] (Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD6", True]))))),
			   FileNameJoin[{"test_files","simulate_data","absRateRev.txt"}, OperatingSystem->$OperatingSystem]->(Toolbox`metabolite["13dpg", "c"] Toolbox`metabolite["nadh", "c"] Toolbox`parameter["GAPD_total"] Toolbox`rateconst["GAPD1", False] Toolbox`rateconst["GAPD2", False] Toolbox`rateconst["GAPD3", False] Toolbox`rateconst["GAPD4", False] Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False])/(Toolbox`rateconst["GAPD1", False] Toolbox`rateconst["GAPD3", False] (Toolbox`metabolite["nadh", "c"] Toolbox`rateconst["GAPD4", False] Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD2", True] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", True])))+Toolbox`metabolite["13dpg", "c"] Toolbox`rateconst["GAPD2", False] (Toolbox`rateconst["GAPD1", False] Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", True]))+Toolbox`metabolite["nadh", "c"] Toolbox`rateconst["GAPD4", False] (Toolbox`rateconst["GAPD3", False] Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD1", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD6", True]))))),
			  FileNameJoin[{"test_files","simulate_data","relRateFor_g3p.txt"}, OperatingSystem->$OperatingSystem]->(Toolbox`metabolite["g3p", "c"] Toolbox`rateconst["GAPD3", True] (Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD2", True] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`metabolite["nad", "c"] Toolbox`rateconst["GAPD1", True] (Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD2", True] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD5", True]+Toolbox`rateconst["GAPD6", True])+Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD5", True] (Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD6", True])))))/(Toolbox`metabolite["g3p", "c"] Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD2", True] Toolbox`rateconst["GAPD3", True] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD1", False] Toolbox`rateconst["GAPD2", True] (Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", True])))+Toolbox`metabolite["nad", "c"] Toolbox`rateconst["GAPD1", True] (Toolbox`metabolite["g3p", "c"] Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD3", True] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD2", True] (Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", True]))+Toolbox`metabolite["g3p", "c"] Toolbox`rateconst["GAPD3", True] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD5", True]+Toolbox`rateconst["GAPD6", True])+Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD5", True] (Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD6", True]))))),
			   FileNameJoin[{"test_files","simulate_data","relRateFor_nad.txt"}, OperatingSystem->$OperatingSystem]->(Toolbox`metabolite["nad", "c"] Toolbox`rateconst["GAPD1", True] (Toolbox`metabolite["g3p", "c"] Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD3", True] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD2", True] (Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", True]))+Toolbox`metabolite["g3p", "c"] Toolbox`rateconst["GAPD3", True] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD5", True]+Toolbox`rateconst["GAPD6", True])+Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD5", True] (Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD6", True])))))/(Toolbox`metabolite["g3p", "c"] Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD2", True] Toolbox`rateconst["GAPD3", True] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD1", False] Toolbox`rateconst["GAPD2", True] (Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", True])))+Toolbox`metabolite["nad", "c"] Toolbox`rateconst["GAPD1", True] (Toolbox`metabolite["g3p", "c"] Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD3", True] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD2", True] (Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", True]))+Toolbox`metabolite["g3p", "c"] Toolbox`rateconst["GAPD3", True] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD5", True]+Toolbox`rateconst["GAPD6", True])+Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD5", True] (Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD6", True]))))),
			  FileNameJoin[{"test_files","simulate_data","relRateFor_pi.txt"}, OperatingSystem->$OperatingSystem]->(Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD5", True] ((Toolbox`rateconst["GAPD1", False]+Toolbox`metabolite["nad", "c"] Toolbox`rateconst["GAPD1", True]) Toolbox`rateconst["GAPD2", True] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD6", True]+Toolbox`metabolite["g3p", "c"] Toolbox`rateconst["GAPD3", True] (Toolbox`rateconst["GAPD2", True] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD6", True]+Toolbox`metabolite["nad", "c"] Toolbox`rateconst["GAPD1", True] (Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD2", True] (Toolbox`rateconst["GAPD4", True]+Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD6", True])))))/(Toolbox`metabolite["g3p", "c"] Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD2", True] Toolbox`rateconst["GAPD3", True] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD1", False] Toolbox`rateconst["GAPD2", True] (Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", True])))+Toolbox`metabolite["nad", "c"] Toolbox`rateconst["GAPD1", True] (Toolbox`metabolite["g3p", "c"] Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD3", True] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD2", True] (Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", True]))+Toolbox`metabolite["g3p", "c"] Toolbox`rateconst["GAPD3", True] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD5", True]+Toolbox`rateconst["GAPD6", True])+Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD5", True] (Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD6", True]))))),
			   FileNameJoin[{"test_files","simulate_data","relRateRev_13dpg.txt"}, OperatingSystem->$OperatingSystem]->(Toolbox`metabolite["13dpg", "c"] Toolbox`rateconst["GAPD2", False] (Toolbox`rateconst["GAPD1", False] Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", True]))+Toolbox`metabolite["nadh", "c"] Toolbox`rateconst["GAPD4", False] (Toolbox`rateconst["GAPD3", False] Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD1", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD6", True])))))/(Toolbox`rateconst["GAPD1", False] Toolbox`rateconst["GAPD3", False] (Toolbox`metabolite["nadh", "c"] Toolbox`rateconst["GAPD4", False] Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD2", True] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", True])))+Toolbox`metabolite["13dpg", "c"] Toolbox`rateconst["GAPD2", False] (Toolbox`rateconst["GAPD1", False] Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", True]))+Toolbox`metabolite["nadh", "c"] Toolbox`rateconst["GAPD4", False] (Toolbox`rateconst["GAPD3", False] Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD1", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD6", True]))))),
			   FileNameJoin[{"test_files","simulate_data","relRateRev_nadh.txt"}, OperatingSystem->$OperatingSystem]->(Toolbox`metabolite["nadh", "c"] Toolbox`rateconst["GAPD4", False] (Toolbox`rateconst["GAPD1", False] Toolbox`rateconst["GAPD3", False] Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`metabolite["13dpg", "c"] Toolbox`rateconst["GAPD2", False] (Toolbox`rateconst["GAPD3", False] Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD1", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD6", True])))))/(Toolbox`rateconst["GAPD1", False] Toolbox`rateconst["GAPD3", False] (Toolbox`metabolite["nadh", "c"] Toolbox`rateconst["GAPD4", False] Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD2", True] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", True])))+Toolbox`metabolite["13dpg", "c"] Toolbox`rateconst["GAPD2", False] (Toolbox`rateconst["GAPD1", False] Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", True]))+Toolbox`metabolite["nadh", "c"] Toolbox`rateconst["GAPD4", False] (Toolbox`rateconst["GAPD3", False] Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD1", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD6", True])))))};

	eqnNameList = {"absRateFor","absRateRev","relRateFor_g3p","relRateFor_nad","relRateFor_pi","relRateRev_13dpg","relRateRev_nadh"};

	eqnValList = {(Toolbox`metabolite["g3p", "c"] Toolbox`metabolite["nad", "c"] Toolbox`metabolite["pi", "c"] Toolbox`parameter["GAPD_total"] Toolbox`rateconst["GAPD1", True] Toolbox`rateconst["GAPD2", True] Toolbox`rateconst["GAPD3", True] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True])/(Toolbox`metabolite["g3p", "c"] Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD2", True] Toolbox`rateconst["GAPD3", True] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD1", False] Toolbox`rateconst["GAPD2", True] (Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", True])))+Toolbox`metabolite["nad", "c"] Toolbox`rateconst["GAPD1", True] (Toolbox`metabolite["g3p", "c"] Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD3", True] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD2", True] (Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", True]))+Toolbox`metabolite["g3p", "c"] Toolbox`rateconst["GAPD3", True] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD5", True]+Toolbox`rateconst["GAPD6", True])+Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD5", True] (Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD6", True]))))),
			  (Toolbox`metabolite["13dpg", "c"] Toolbox`metabolite["nadh", "c"] Toolbox`parameter["GAPD_total"] Toolbox`rateconst["GAPD1", False] Toolbox`rateconst["GAPD2", False] Toolbox`rateconst["GAPD3", False] Toolbox`rateconst["GAPD4", False] Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False])/(Toolbox`rateconst["GAPD1", False] Toolbox`rateconst["GAPD3", False] (Toolbox`metabolite["nadh", "c"] Toolbox`rateconst["GAPD4", False] Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD2", True] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", True])))+Toolbox`metabolite["13dpg", "c"] Toolbox`rateconst["GAPD2", False] (Toolbox`rateconst["GAPD1", False] Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", True]))+Toolbox`metabolite["nadh", "c"] Toolbox`rateconst["GAPD4", False] (Toolbox`rateconst["GAPD3", False] Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD1", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD6", True]))))),
			  (Toolbox`metabolite["g3p", "c"] Toolbox`rateconst["GAPD3", True] (Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD2", True] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`metabolite["nad", "c"] Toolbox`rateconst["GAPD1", True] (Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD2", True] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD5", True]+Toolbox`rateconst["GAPD6", True])+Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD5", True] (Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD6", True])))))/(Toolbox`metabolite["g3p", "c"] Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD2", True] Toolbox`rateconst["GAPD3", True] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD1", False] Toolbox`rateconst["GAPD2", True] (Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", True])))+Toolbox`metabolite["nad", "c"] Toolbox`rateconst["GAPD1", True] (Toolbox`metabolite["g3p", "c"] Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD3", True] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD2", True] (Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", True]))+Toolbox`metabolite["g3p", "c"] Toolbox`rateconst["GAPD3", True] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD5", True]+Toolbox`rateconst["GAPD6", True])+Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD5", True] (Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD6", True]))))),
			  (Toolbox`metabolite["nad", "c"] Toolbox`rateconst["GAPD1", True] (Toolbox`metabolite["g3p", "c"] Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD3", True] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD2", True] (Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", True]))+Toolbox`metabolite["g3p", "c"] Toolbox`rateconst["GAPD3", True] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD5", True]+Toolbox`rateconst["GAPD6", True])+Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD5", True] (Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD6", True])))))/(Toolbox`metabolite["g3p", "c"] Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD2", True] Toolbox`rateconst["GAPD3", True] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD1", False] Toolbox`rateconst["GAPD2", True] (Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", True])))+Toolbox`metabolite["nad", "c"] Toolbox`rateconst["GAPD1", True] (Toolbox`metabolite["g3p", "c"] Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD3", True] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD2", True] (Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", True]))+Toolbox`metabolite["g3p", "c"] Toolbox`rateconst["GAPD3", True] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD5", True]+Toolbox`rateconst["GAPD6", True])+Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD5", True] (Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD6", True]))))),
		  	(Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD5", True] ((Toolbox`rateconst["GAPD1", False]+Toolbox`metabolite["nad", "c"] Toolbox`rateconst["GAPD1", True]) Toolbox`rateconst["GAPD2", True] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD6", True]+Toolbox`metabolite["g3p", "c"] Toolbox`rateconst["GAPD3", True] (Toolbox`rateconst["GAPD2", True] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD6", True]+Toolbox`metabolite["nad", "c"] Toolbox`rateconst["GAPD1", True] (Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD2", True] (Toolbox`rateconst["GAPD4", True]+Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD6", True])))))/(Toolbox`metabolite["g3p", "c"] Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD2", True] Toolbox`rateconst["GAPD3", True] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD1", False] Toolbox`rateconst["GAPD2", True] (Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", True])))+Toolbox`metabolite["nad", "c"] Toolbox`rateconst["GAPD1", True] (Toolbox`metabolite["g3p", "c"] Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD3", True] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD2", True] (Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD4", True] Toolbox`rateconst["GAPD5", True] Toolbox`rateconst["GAPD6", True]+Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", True]))+Toolbox`metabolite["g3p", "c"] Toolbox`rateconst["GAPD3", True] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD5", True]+Toolbox`rateconst["GAPD6", True])+Toolbox`metabolite["pi", "c"] Toolbox`rateconst["GAPD5", True] (Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD6", True]))))),
		  	(Toolbox`metabolite["13dpg", "c"] Toolbox`rateconst["GAPD2", False] (Toolbox`rateconst["GAPD1", False] Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", True]))+Toolbox`metabolite["nadh", "c"] Toolbox`rateconst["GAPD4", False] (Toolbox`rateconst["GAPD3", False] Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD1", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD6", True])))))/(Toolbox`rateconst["GAPD1", False] Toolbox`rateconst["GAPD3", False] (Toolbox`metabolite["nadh", "c"] Toolbox`rateconst["GAPD4", False] Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD2", True] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", True])))+Toolbox`metabolite["13dpg", "c"] Toolbox`rateconst["GAPD2", False] (Toolbox`rateconst["GAPD1", False] Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", True]))+Toolbox`metabolite["nadh", "c"] Toolbox`rateconst["GAPD4", False] (Toolbox`rateconst["GAPD3", False] Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD1", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD6", True]))))),
		  	(Toolbox`metabolite["nadh", "c"] Toolbox`rateconst["GAPD4", False] (Toolbox`rateconst["GAPD1", False] Toolbox`rateconst["GAPD3", False] Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`metabolite["13dpg", "c"] Toolbox`rateconst["GAPD2", False] (Toolbox`rateconst["GAPD3", False] Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD1", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD6", True])))))/(Toolbox`rateconst["GAPD1", False] Toolbox`rateconst["GAPD3", False] (Toolbox`metabolite["nadh", "c"] Toolbox`rateconst["GAPD4", False] Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD2", True] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", True])))+Toolbox`metabolite["13dpg", "c"] Toolbox`rateconst["GAPD2", False] (Toolbox`rateconst["GAPD1", False] Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD4", True] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", True]))+Toolbox`metabolite["nadh", "c"] Toolbox`rateconst["GAPD4", False] (Toolbox`rateconst["GAPD3", False] Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD1", False] (Toolbox`rateconst["GAPD5", False] Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD3", False] (Toolbox`rateconst["GAPD5", False]+Toolbox`rateconst["GAPD6", False]+Toolbox`rateconst["GAPD6", True])))))};

	eqnValListPy = {"(d[2]*d[3]*d[5]*d[6]*x[1]*x[11]*x[3]*x[5]*x[7]*x[9])/(d[2]*d[5]*x[11]*x[3]*x[5]*x[7]*x[9] + x[0]*x[3]*(x[4]*(x[10]*x[8] + x[7]*(x[11] + x[8])) + d[5]*x[11]*x[7]*x[9]) + d[3]*x[1]*(d[2]*d[5]*x[11]*x[5]*x[7]*x[9] + x[3]*(x[4]*(x[10]*x[8] + x[7]*(x[11] + x[8])) + d[5]*x[11]*x[7]*x[9] + d[2]*x[5]*(x[10]*x[8] + d[5]*(x[10] + x[11])*x[9] + x[7]*(x[11] + x[8] + d[5]*x[9])))))",
				"(d[1]*d[4]*d[6]*x[0]*x[10]*x[2]*x[4]*x[6]*x[8])/(x[0]*x[4]*(d[4]*x[10]*x[6]*x[8] + x[3]*(x[10]*x[8] + x[7]*(x[11] + x[8]))) + d[1]*x[2]*(x[0]*x[4]*(x[10]*x[8] + x[7]*(x[11] + x[8])) + d[4]*x[6]*(x[10]*x[4]*x[8] + x[0]*(x[10]*x[8] + x[4]*(x[10] + x[11] + x[8])))))",
				"(d[2]*x[5]*(d[5]*x[11]*x[3]*x[7]*x[9] + d[3]*x[1]*(d[5]*x[11]*x[7]*x[9] + x[3]*(x[10]*x[8] + d[5]*(x[10] + x[11])*x[9] + x[7]*(x[11] + x[8] + d[5]*x[9])))))/(d[2]*d[5]*x[11]*x[3]*x[5]*x[7]*x[9] + x[0]*x[3]*(x[4]*(x[10]*x[8] + x[7]*(x[11] + x[8])) + d[5]*x[11]*x[7]*x[9]) + d[3]*x[1]*(d[2]*d[5]*x[11]*x[5]*x[7]*x[9] + x[3]*(x[4]*(x[10]*x[8] + x[7]*(x[11] + x[8])) + d[5]*x[11]*x[7]*x[9] + d[2]*x[5]*(x[10]*x[8] + d[5]*(x[10] + x[11])*x[9] + x[7]*(x[11] + x[8] + d[5]*x[9])))))",
				"(d[3]*x[1]*(d[2]*d[5]*x[11]*x[5]*x[7]*x[9] + x[3]*(x[4]*(x[10]*x[8] + x[7]*(x[11] + x[8])) + d[5]*x[11]*x[7]*x[9] + d[2]*x[5]*(x[10]*x[8] + d[5]*(x[10] + x[11])*x[9] + x[7]*(x[11] + x[8] + d[5]*x[9])))))/(d[2]*d[5]*x[11]*x[3]*x[5]*x[7]*x[9] + x[0]*x[3]*(x[4]*(x[10]*x[8] + x[7]*(x[11] + x[8])) + d[5]*x[11]*x[7]*x[9]) + d[3]*x[1]*(d[2]*d[5]*x[11]*x[5]*x[7]*x[9] + x[3]*(x[4]*(x[10]*x[8] + x[7]*(x[11] + x[8])) + d[5]*x[11]*x[7]*x[9] + d[2]*x[5]*(x[10]*x[8] + d[5]*(x[10] + x[11])*x[9] + x[7]*(x[11] + x[8] + d[5]*x[9])))))",
				"(d[5]*((x[0] + d[3]*x[1])*x[11]*x[3]*x[7] + d[2]*x[5]*(x[11]*x[3]*x[7] + d[3]*x[1]*(x[11]*x[7] + x[3]*(x[10] + x[11] + x[7]))))*x[9])/(d[2]*d[5]*x[11]*x[3]*x[5]*x[7]*x[9] + x[0]*x[3]*(x[4]*(x[10]*x[8] + x[7]*(x[11] + x[8])) + d[5]*x[11]*x[7]*x[9]) + d[3]*x[1]*(d[2]*d[5]*x[11]*x[5]*x[7]*x[9] + x[3]*(x[4]*(x[10]*x[8] + x[7]*(x[11] + x[8])) + d[5]*x[11]*x[7]*x[9] + d[2]*x[5]*(x[10]*x[8] + d[5]*(x[10] + x[11])*x[9] + x[7]*(x[11] + x[8] + d[5]*x[9])))))",
				"(d[1]*x[2]*(x[0]*x[4]*(x[10]*x[8] + x[7]*(x[11] + x[8])) + d[4]*x[6]*(x[10]*x[4]*x[8] + x[0]*(x[10]*x[8] + x[4]*(x[10] + x[11] + x[8])))))/(x[0]*x[4]*(d[4]*x[10]*x[6]*x[8] + x[3]*(x[10]*x[8] + x[7]*(x[11] + x[8]))) + d[1]*x[2]*(x[0]*x[4]*(x[10]*x[8] + x[7]*(x[11] + x[8])) + d[4]*x[6]*(x[10]*x[4]*x[8] + x[0]*(x[10]*x[8] + x[4]*(x[10] + x[11] + x[8])))))",
				"(d[4]*x[6]*(x[0]*x[10]*x[4]*x[8] + d[1]*x[2]*(x[10]*x[4]*x[8] + x[0]*(x[10]*x[8] + x[4]*(x[10] + x[11] + x[8])))))/(x[0]*x[4]*(d[4]*x[10]*x[6]*x[8] + x[3]*(x[10]*x[8] + x[7]*(x[11] + x[8]))) + d[1]*x[2]*(x[0]*x[4]*(x[10]*x[8] + x[7]*(x[11] + x[8])) + d[4]*x[6]*(x[10]*x[4]*x[8] + x[0]*(x[10]*x[8] + x[4]*(x[10] + x[11] + x[8])))))"};

	allCatalyticReactions = {Toolbox`reaction["GAPD1", {Toolbox`enzyme[{"ID" -> "GAPD", "Compartment" -> "c", "BoundCatalytic" -> {}, "BoundActivators" -> {}, "BoundInhibitors" -> {}, "CatalyticSites" -> DirectedInfinity[1], "ActivationSites" -> 0, "InhibitionSites" -> 0}], Toolbox`metabolite["nad", "c"]}, {Toolbox`enzyme[{"ID" -> "GAPD", "Compartment" -> "c", "BoundCatalytic" -> {Toolbox`Private`wrap[Toolbox`metabolite]["nad", "c"]}, "BoundActivators" -> {}, "BoundInhibitors" -> {}, "CatalyticSites" -> DirectedInfinity[1], "ActivationSites" -> 0, "InhibitionSites" -> 0}]}, {1, 1, 1}, True],Toolbox`reaction["GAPD2", {Toolbox`enzyme[{"ID" -> "GAPD", "Compartment" -> "c", "BoundCatalytic" -> {Toolbox`Private`wrap[Toolbox`metabolite]["13dpg", "c"]}, "BoundActivators" -> {}, "BoundInhibitors" -> {}, "CatalyticSites" -> DirectedInfinity[1], "ActivationSites" -> 0, "InhibitionSites" -> 0}]}, {Toolbox`enzyme[{"ID" -> "GAPD", "Compartment" -> "c", "BoundCatalytic" -> {}, "BoundActivators" -> {}, "BoundInhibitors" -> {}, "CatalyticSites" -> DirectedInfinity[1], "ActivationSites" -> 0, "InhibitionSites" -> 0}], Toolbox`metabolite["13dpg", "c"]}, {1, 1, 1}, True],
						Toolbox`reaction["GAPD3", {Toolbox`enzyme[{"ID" -> "GAPD", "Compartment" -> "c", "BoundCatalytic" -> {Toolbox`Private`wrap[Toolbox`metabolite]["nad", "c"]}, "BoundActivators" -> {}, "BoundInhibitors" -> {}, "CatalyticSites" -> DirectedInfinity[1], "ActivationSites" -> 0, "InhibitionSites" -> 0}], Toolbox`metabolite["g3p", "c"]}, {Toolbox`enzyme[{"ID" -> "GAPD", "Compartment" -> "c", "BoundCatalytic" -> {Toolbox`Private`wrap[Toolbox`metabolite]["nad", "c"], Toolbox`Private`wrap[Toolbox`metabolite]["g3p", "c"]}, "BoundActivators" -> {}, "BoundInhibitors" -> {}, "CatalyticSites" -> DirectedInfinity[1], "ActivationSites" -> 0, "InhibitionSites" -> 0}]}, {1, 1, 1}, True],Toolbox`reaction["GAPD4", {Toolbox`enzyme[{"ID" -> "GAPD", "Compartment" -> "c", "BoundCatalytic" -> {Toolbox`Private`wrap[Toolbox`metabolite]["13dpg", "c"], Toolbox`Private`wrap[Toolbox`metabolite]["nadh", "c"]}, "BoundActivators" -> {}, "BoundInhibitors" -> {}, "CatalyticSites" -> DirectedInfinity[1], "ActivationSites" -> 0, "InhibitionSites" -> 0}]}, {Toolbox`enzyme[{"ID" -> "GAPD", "Compartment" -> "c", "BoundCatalytic" -> {Toolbox`Private`wrap[Toolbox`metabolite]["13dpg", "c"]}, "BoundActivators" -> {}, "BoundInhibitors" -> {}, "CatalyticSites" -> DirectedInfinity[1], "ActivationSites" -> 0, "InhibitionSites" -> 0}], Toolbox`metabolite["nadh", "c"]}, {1, 1, 1}, True],
						Toolbox`reaction["GAPD5", {Toolbox`enzyme[{"ID" -> "GAPD", "Compartment" -> "c", "BoundCatalytic" -> {Toolbox`Private`wrap[Toolbox`metabolite]["nad", "c"], Toolbox`Private`wrap[Toolbox`metabolite]["g3p", "c"]}, "BoundActivators" -> {}, "BoundInhibitors" -> {}, "CatalyticSites" -> DirectedInfinity[1], "ActivationSites" -> 0, "InhibitionSites" -> 0}], Toolbox`metabolite["pi", "c"]}, {Toolbox`enzyme[{"ID" -> "GAPD", "Compartment" -> "c", "BoundCatalytic" -> {Toolbox`Private`wrap[Toolbox`metabolite]["nad", "c"], Toolbox`Private`wrap[Toolbox`metabolite]["g3p", "c"], Toolbox`Private`wrap[Toolbox`metabolite]["pi", "c"]}, "BoundActivators" -> {}, "BoundInhibitors" -> {}, "CatalyticSites" -> DirectedInfinity[1], "ActivationSites" -> 0, "InhibitionSites" -> 0}]}, {1, 1, 1}, True],Toolbox`reaction["GAPD6", {Toolbox`enzyme[{"ID" -> "GAPD", "Compartment" -> "c", "BoundCatalytic" -> {Toolbox`Private`wrap[Toolbox`metabolite]["nad", "c"], Toolbox`Private`wrap[Toolbox`metabolite]["g3p", "c"], Toolbox`Private`wrap[Toolbox`metabolite]["pi", "c"]}, "BoundActivators" -> {}, "BoundInhibitors" -> {}, "CatalyticSites" -> DirectedInfinity[1], "ActivationSites" -> 0, "InhibitionSites" -> 0}]}, {Toolbox`enzyme[{"ID" -> "GAPD", "Compartment" -> "c", "BoundCatalytic" -> {Toolbox`Private`wrap[Toolbox`metabolite]["13dpg", "c"], Toolbox`Private`wrap[Toolbox`metabolite]["nadh", "c"]}, "BoundActivators" -> {}, "BoundInhibitors" -> {}, "CatalyticSites" -> DirectedInfinity[1], "ActivationSites" -> 0, "InhibitionSites" -> 0}]}, {1, 1}, True]};
						
	unifiedRateConstList = {Toolbox`rateconst["GAPD1", True]->Toolbox`rateconst["GAPD1", True],Toolbox`rateconst["GAPD1", False]->Toolbox`rateconst["GAPD1", False],Toolbox`rateconst["GAPD2", True]->Toolbox`rateconst["GAPD2", True],Toolbox`rateconst["GAPD2", False]->Toolbox`rateconst["GAPD2", False],Toolbox`rateconst["GAPD3", True]->Toolbox`rateconst["GAPD3", True],Toolbox`rateconst["GAPD3", False]->Toolbox`rateconst["GAPD3", False],Toolbox`rateconst["GAPD4", True]->Toolbox`rateconst["GAPD4", True],Toolbox`rateconst["GAPD4", False]->Toolbox`rateconst["GAPD4", False],Toolbox`rateconst["GAPD5", True]->Toolbox`rateconst["GAPD5", True],Toolbox`rateconst["GAPD5", False]->Toolbox`rateconst["GAPD5", False],Toolbox`rateconst["GAPD6", True]->Toolbox`rateconst["GAPD6", True],Toolbox`rateconst["GAPD6", False]->Toolbox`rateconst["GAPD6", False]};


	Return[{rxn, metsFull, rateConstsSub, metsSub, eTotal, logStepSize,nonKmParamWeight,
			allCatalyticReactions, unifiedRateConstList, fileList, fileListSub, eqnNameList, 
			eqnValList, eqnValListPy}];
];


getInputTestSimulateInhibDataTALA2[] := Block[{rxn, metsFull, metSatForSub, metSatRevSub, inhibitionList, 
	kmList, assumedSaturatingConc, eTotal, logStepSize, activeIsoSub, bufferInfo, ionCharge,fileList,
	bufferInfoDataPath, ionChargeDataPath},
	
	rxn = Toolbox`reaction["TALA2", {Toolbox`metabolite["e4p", "c"], Toolbox`metabolite["f6p", "c"]}, {Toolbox`metabolite["g3p", "c"], Toolbox`metabolite["s7p", "c"]}, {1, 1, 1, 1}, True];
	metsFull = {Toolbox`metabolite["e4p", "c"],Toolbox`metabolite["f6p", "c"],Toolbox`metabolite["g3p", "c"],Toolbox`metabolite["s7p", "c"],Toolbox`metabolite["pi", "c"]};
	metSatForSub = {Toolbox`metabolite["e4p", "c"]->\[Infinity],Toolbox`metabolite["f6p", "c"]->\[Infinity]};
	metSatRevSub = {Toolbox`metabolite["g3p", "c"]->\[Infinity],Toolbox`metabolite["s7p", "c"]->\[Infinity]};
	inhibitionList = {{"Kic","pi",0.019`,{{"e4p",Null}},{{"Competitive",Null,Null,"f6p",Null}},"M",8.5`,30.`,{{"glygly",0.05`}},{}},{"Kic","pi",0.019`,{{"f6p",Null}},{{"Competitive",Null,Null,"e4p",Null}},"M",8.5`,30.`,{{"glygly",0.05`}},{}},{"Kic","pi",0.019`,{{"g3p",Null}},{{"Competitive",Null,Null,"s7p",Null}},"M",8.5`,30.`,{{"glygly",0.05`}},{}},{"Kic","pi",0.019`,{{"s7p",Null}},{{"Competitive",Null,Null,"g3p",Null}},"M",8.5`,30.`,{{"glygly",0.05`}},{}}};
	kmList = {{"g3p",0.000037999999999999995`,{{"f6p",0.0285`}},"M",8.5`,30.`,{{"glygly",0.05`}},{}},{"e4p",0.00009`,{{"f6p",0.0285`}},"M",8.5`,30.`,{{"glygly",0.05`}},{}},{"r5p",0.031`,{{"f6p",0.0285`}},"M",8.5`,30.`,{{"glygly",0.05`}},{}},{"f6p",0.0012000000000000001`,{{"g3p",0.0038`}},"M",8.5`,30.`,{{"glygly",0.05`}},{}},{"s7p",0.000285`,{{"g3p",0.0038`}},"M",8.5`,30.`,{{"glygly",0.05`}},{}}};
	assumedSaturatingConc = 0.01;
	eTotal = 1;
	logStepSize=0.2;
	activeIsoSub = {Toolbox`metabolite["e4p", "c"]->Toolbox`metabolite["e4p", "c"],Toolbox`metabolite["f6p", "c"]->Toolbox`metabolite["f6p", "c"],Toolbox`metabolite["g3p", "c"]->Toolbox`metabolite["g3p", "c"],Toolbox`metabolite["s7p", "c"]->Toolbox`metabolite["s7p", "c"],Toolbox`metabolite["pi", "c"]->Toolbox`metabolite["pi", "c"]};

	bufferInfoDataPath = FileNameJoin[{"test_files","simulate_data","buffer_info.csv"}, OperatingSystem->$OperatingSystem];
	ionChargeDataPath = FileNameJoin[{"test_files","simulate_data","ion_charge.csv"}, OperatingSystem->$OperatingSystem];

	bufferInfo = getBufferInfoData[bufferInfoDataPath];
	ionCharge = getIonData[ionChargeDataPath];
	fileList = {FileNameJoin[{"test_files","simulate_data","absRateFor.txt"}, OperatingSystem->$OperatingSystem],
				FileNameJoin[{"test_files","simulate_data","absRateRev.txt"}, OperatingSystem->$OperatingSystem],
				FileNameJoin[{"test_files","simulate_data","relRateFor_e4p.txt"}, OperatingSystem->$OperatingSystem],
				FileNameJoin[{"test_files","simulate_data","relRateFor_f6p.txt"}, OperatingSystem->$OperatingSystem],
				FileNameJoin[{"test_files","simulate_data","relRateRev_g3p.txt"}, OperatingSystem->$OperatingSystem],
				FileNameJoin[{"test_files","simulate_data","relRateRev_s7p.txt"}, OperatingSystem->$OperatingSystem],
				FileNameJoin[{"test_files","simulate_data","haldaneRatio.txt"}, OperatingSystem->$OperatingSystem],
				FileNameJoin[{"test_files","simulate_data","dKdRatio.txt"}, OperatingSystem->$OperatingSystem],
				FileNameJoin[{"test_files","simulate_data","inhibRatio.txt"}, OperatingSystem->$OperatingSystem]};
	
	Return[{rxn, metsFull, metSatForSub, metSatRevSub, inhibitionList, kmList, assumedSaturatingConc, eTotal,
			   logStepSize, activeIsoSub, bufferInfo, ionCharge,fileList}];
];


getInputTestSimulateInhibDataG3PD2[] := Block[{rxn, metsFull, metSatForSub, metSatRevSub, inhibitionList, 
	kmList, assumedSaturatingConc, eTotal, logStepSize, activeIsoSub, bufferInfo, ionCharge,fileList,
	bufferInfoDataPath, ionChargeDataPath},
	
	rxn = Toolbox`reaction["G3PD2", {Toolbox`metabolite["glyc3p", "c"], Toolbox`metabolite["nadp", "c"]}, {Toolbox`metabolite["dhap", "c"], Toolbox`metabolite["h", "c"], Toolbox`metabolite["nadph", "c"]}, {1, 1, 1, 1, 1}, True];
	metsFull ={Toolbox`metabolite["dhap", "c"],Toolbox`metabolite["glyc3p", "c"],Toolbox`metabolite["nadp", "c"],Toolbox`metabolite["nadph", "c"]};
	metSatForSub = {Toolbox`metabolite["glyc3p", "c"]->\[Infinity],Toolbox`metabolite["nadp", "c"]->\[Infinity]};
	metSatRevSub = {Toolbox`metabolite["dhap", "c"]->\[Infinity],Toolbox`metabolite["nadph", "c"]->\[Infinity]};
	inhibitionList = {{"Kic","glyc3p",4.2`*^-6,{{"nadph",0.0001`}},{{"Competitive",Null,Null,"dhap",Null}},"M",7.4`,23.`,{{"trishcl",0.1`}},{}},{"Kincu","glyc3p",6.5`*^-6,{{"dhap",0.0001`}},{{"NonCompetitive",Null,Null,"nadph",Null}},"M",7.4`,23.`,{{"trishcl",0.1`}},{}},{"Kincc","glyc3p",2.4999999999999998`*^-6,{{"dhap",0.0001`}},{{"NonCompetitive",Null,Null,"nadph",Null}},"M",7.4`,23.`,{{"trishcl",0.1`}},{}},{"Kincu","nadp",0.0013000000000000002`,{{"nadph",0.00001`}},{{"NonCompetitive",Null,Null,"dhap",Null}},"M",7.4`,23.`,{{"trishcl",0.1`}},{}},{"Kincc","nadp",0.0013000000000000002`,{{"nadph",0.00001`}},{{"NonCompetitive",Null,Null,"dhap",Null}},"M",7.4`,23.`,{{"trishcl",0.1`}},{}},{"Kic","nadp",0.000187`,{{"dhap",0.002`}},{{"Competitive",Null,Null,"nadph",Null}},"M",7.4`,23.`,{{"trishcl",0.1`}},{}},{"Kic","dhap",0.000037999999999999995`,{{"nadp",0.002`}},{{"Competitive",Null,Null,"glyc3p",Null}},"M",7.4`,23.`,{{"trishcl",0.1`}},{}},{"Kincu","dhap",0.00024000000000000003`,{{"glyc3p",0.0001`}},{{"NonCompetitive",Null,Null,"nadp",Null}},"M",7.4`,23.`,{{"trishcl",0.1`}},{}},{"Kincc","dhap",0.00012000000000000002`,{{"glyc3p",0.0001`}},{{"NonCompetitive",Null,Null,"nadp",Null}},"M",7.4`,23.`,{{"trishcl",0.1`}},{}},{"Kincu","nadph",8.`*^-7,{{"nadp",0.0001`}},{{"NonCompetitive",Null,Null,"glyc3p",Null}},"M",7.4`,23.`,{{"trishcl",0.1`}},{}},{"Kincc","nadph",6.`*^-7,{{"nadp",0.0001`}},{{"NonCompetitive",Null,Null,"glyc3p",Null}},"M",7.4`,23.`,{{"trishcl",0.1`}},{}},{"Kic","nadph",4.`*^-7,{{"glyc3p",0.0002`}},{{"Competitive",Null,Null,"nadp",Null}},"M",7.4`,23.`,{{"trishcl",0.1`}},{}}};
	kmList = {{"nadph",3.3999999999999996`*^-6,{},"M",7.4`,23.`,{{"trishcl",0.1`}},{}},{"dhap",0.00018`,{},"M",7.4`,23.`,{{"trishcl",0.1`}},{}},{"nadp",0.000165`,{},"M",7.4`,23.`,{{"trishcl",0.1`}},{}},{"glyc3p",0.000030000000000000004`,{},"M",7.4`,23.`,{{"trishcl",0.1`}},{}}};
	assumedSaturatingConc = 0.01;
	eTotal = 1;
	logStepSize=0.5;
	activeIsoSub = {Toolbox`metabolite["dhap", "c"]->Toolbox`metabolite["dhap", "c"],Toolbox`metabolite["glyc3p", "c"]->Toolbox`metabolite["glyc3p", "c"],Toolbox`metabolite["nadp", "c"]->Toolbox`metabolite["nadp", "c"],Toolbox`metabolite["nadph", "c"]->Toolbox`metabolite["nadph", "c"]};
	
	bufferInfoDataPath = FileNameJoin[{"test_files","simulate_data","buffer_info.csv"}, OperatingSystem->$OperatingSystem];
	ionChargeDataPath = FileNameJoin[{"test_files","simulate_data","ion_charge.csv"}, OperatingSystem->$OperatingSystem];

	bufferInfo = getBufferInfoData[bufferInfoDataPath];
	ionCharge = getIonData[ionChargeDataPath];
	fileList = {FileNameJoin[{"test_files","simulate_data","absRateFor.txt"}, OperatingSystem->$OperatingSystem],
				FileNameJoin[{"test_files","simulate_data","absRateRev.txt"}, OperatingSystem->$OperatingSystem],
				FileNameJoin[{"test_files","simulate_data","relRateFor_glyc3p.txt"}, OperatingSystem->$OperatingSystem],
				FileNameJoin[{"test_files","simulate_data","relRateFor_nadp.txt"}, OperatingSystem->$OperatingSystem],
				FileNameJoin[{"test_files","simulate_data","relRateRev_dhap.txt"}, OperatingSystem->$OperatingSystem],
				FileNameJoin[{"test_files","simulate_data","relRateRev_nadph.txt"}, OperatingSystem->$OperatingSystem],
				FileNameJoin[{"test_files","simulate_data","prod_inhib_dhap.txt"}, OperatingSystem->$OperatingSystem],
				FileNameJoin[{"test_files","simulate_data","prod_inhib_nadph.txt"}, OperatingSystem->$OperatingSystem],
				FileNameJoin[{"test_files","simulate_data","prod_inhib_glyc3p.txt"}, OperatingSystem->$OperatingSystem],
				FileNameJoin[{"test_files","simulate_data","prod_inhib_nadp.txt"}, OperatingSystem->$OperatingSystem],
				FileNameJoin[{"test_files","simulate_data","haldaneRatio.txt"}, OperatingSystem->$OperatingSystem]};
	
	Return[{rxn, metsFull, metSatForSub, metSatRevSub, inhibitionList, kmList, assumedSaturatingConc, eTotal,
			   logStepSize, activeIsoSub, bufferInfo, ionCharge,fileList}];
];


getInputTestSimulateL0DataPFK1[] := Block[{L0Ratio,L0Value, KeqEquilibrator, metsFull, rateConstsSub, metsSub, eTotal, nonKmParamWeight, 
	inputPath, fileList, fileListSub, eqnNameList, eqnValList, eqnValListPy, pHandT},
	
	L0Ratio = Toolbox`rateconst["PFK1_TransitionStep", False]/Toolbox`rateconst["PFK1_TransitionStep", True];
	L0Value = 4.`*^6;
	
	KeqEquilibrator=1;
	
	metsFull = {Toolbox`metabolite["adp", "c"],Toolbox`metabolite["atp", "c"],Toolbox`metabolite["f6p", "c"],Toolbox`metabolite["fdp", "c"],Toolbox`metabolite["gdp", "c"],Toolbox`metabolite["pep", "c"]};
	
	rateConstsSub={Toolbox`rateconst["PFK11", False]->"x<0>",Toolbox`rateconst["PFK11", True]->"x<1>",Toolbox`rateconst["PFK12", False]->"x<2>",Toolbox`rateconst["PFK12", True]->"x<3>",Toolbox`rateconst["PFK13", False]->"x<4>",Toolbox`rateconst["PFK13", True]->"x<5>",Toolbox`rateconst["PFK14", False]->"x<6>",Toolbox`rateconst["PFK14", True]->"x<7>",Toolbox`rateconst["PFK15", False]->"x<8>",Toolbox`rateconst["PFK15", True]->"x<9>",Toolbox`rateconst["PFK15$11", False]->"x<10>",Toolbox`rateconst["PFK15$11", True]->"x<11>",Toolbox`rateconst["PFK1_Activation_gdp", False]->"x<12>",Toolbox`rateconst["PFK1_Activation_gdp", True]->"x<13>",Toolbox`rateconst["PFK1_Inhibition_pep", False]->"x<14>",Toolbox`rateconst["PFK1_Inhibition_pep", True]->"x<15>",Toolbox`rateconst["PFK1_Kic_adp_1_atp", False]->"x<16>",Toolbox`rateconst["PFK1_Kic_adp_1_atp", True]->"x<17>",Toolbox`rateconst["PFK1_Kic_adp_2_atp", False]->"x<18>",Toolbox`rateconst["PFK1_Kic_adp_2_atp", True]->"x<19>",Toolbox`rateconst["PFK1_TransitionStep", False]->"x<20>",Toolbox`rateconst["PFK1_TransitionStep", True]->"x<21>"};
	metsSub = {Toolbox`Keq["PFK1"]->"d<0>",Toolbox`metabolite["adp", "c"]->"d<1>",Toolbox`metabolite["atp", "c"]->"d<2>",Toolbox`metabolite["f6p", "c"]->"d<3>",Toolbox`metabolite["fdp", "c"]->"d<4>",Toolbox`metabolite["gdp", "c"]->"d<5>",Toolbox`metabolite["pep", "c"]->"d<6>",Toolbox`parameter["GAPD_total"]->"d<7>",Toolbox`parameter["pH"]->"d<8>",Toolbox`parameter["Temp"]->"d<9>"};
	eTotal = 1;
	nonKmParamWeight = 11;
	fileList = {};
	fileListSub = {};
	eqnNameList = {};
	eqnValList = {};
	eqnValListPy = {};
	pHandT ={8.5,30};
	
	Return[{L0Ratio,L0Value, KeqEquilibrator, metsFull, rateConstsSub, metsSub, eTotal, nonKmParamWeight, 
			fileList, fileListSub, eqnNameList, eqnValList, eqnValListPy, pHandT}];
];
