(* Created with the Wolfram Language for Students - Personal Use Only : www.wolfram.com *)
MASSmodel[{"ID" -> "MASSmodel$11", "Constraints" -> {}, 
  "InitialConditions" -> {}, "Parameters" -> {parameter["Volume", "c"] -> 1}, 
  "GPR" -> {}, "BoundaryConditions" -> {}, "Constant" -> {}, 
  "CustomODE" -> {}, "Name" -> "MASSmodel$11", "ElementalComposition" -> 
   {enzyme[{"ID" -> "ANS", "Compartment" -> "c", "BoundCatalytic" -> {}, 
       "BoundActivators" -> {}, "BoundInhibitors" -> {}, 
       "CatalyticSites" -> Infinity, "ActivationSites" -> 0, 
       "InhibitionSites" -> 0}] -> "&ANS&", 
    enzyme[{"ID" -> "ANS", "Compartment" -> "c", "BoundCatalytic" -> 
        {Toolbox`Private`wrap[metabolite]["anth", "c"]}, 
       "BoundActivators" -> {}, "BoundInhibitors" -> {}, 
       "CatalyticSites" -> Infinity, "ActivationSites" -> 0, 
       "InhibitionSites" -> 0}] -> "&ANS&", 
    enzyme[{"ID" -> "ANS", "Compartment" -> "c", "BoundCatalytic" -> 
        {Toolbox`Private`wrap[metabolite]["gln_", "L"]}, 
       "BoundActivators" -> {}, "BoundInhibitors" -> {}, 
       "CatalyticSites" -> Infinity, "ActivationSites" -> 0, 
       "InhibitionSites" -> 0}] -> "&ANS&", 
    enzyme[{"ID" -> "ANS", "Compartment" -> "c", "BoundCatalytic" -> 
        {Toolbox`Private`wrap[metabolite]["anth", "c"], 
         Toolbox`Private`wrap[metabolite]["pyr", "c"]}, 
       "BoundActivators" -> {}, "BoundInhibitors" -> {}, 
       "CatalyticSites" -> Infinity, "ActivationSites" -> 0, 
       "InhibitionSites" -> 0}] -> "&ANS&", 
    enzyme[{"ID" -> "ANS", "Compartment" -> "c", "BoundCatalytic" -> 
        {Toolbox`Private`wrap[metabolite]["chor", "c"], 
         Toolbox`Private`wrap[metabolite]["gln_", "L"]}, 
       "BoundActivators" -> {}, "BoundInhibitors" -> {}, 
       "CatalyticSites" -> Infinity, "ActivationSites" -> 0, 
       "InhibitionSites" -> 0}] -> "&ANS&", 
    enzyme[{"ID" -> "ANS", "Compartment" -> "c", "BoundCatalytic" -> 
        {Toolbox`Private`wrap[metabolite]["anth", "c"], 
         Toolbox`Private`wrap[metabolite]["pyr", "c"], 
         Toolbox`Private`wrap[metabolite]["glu_", "L"]}, 
       "BoundActivators" -> {}, "BoundInhibitors" -> {}, 
       "CatalyticSites" -> Infinity, "ActivationSites" -> 0, 
       "InhibitionSites" -> 0}] -> "&ANS&", metabolite["anth", "c"] -> 
     "&anth&", metabolite["chor", "c"] -> "&chor&", 
    metabolite["gln__L", "c"] -> "&gln__L&", metabolite["glu__L", "c"] -> 
     "&glu__L&", metabolite["pyr", "c"] -> "&pyr&"}, "Notes" -> "", 
  "Annotations" -> {}, "Ignore" -> {}, "UnitChecking" -> False, 
  "Synonyms" -> {}, "Events" -> {}, "CustomRateLaws" -> {}, 
  "Stoichiometry" -> SparseArray[Automatic, {13, 7}, 0, 
    {1, {{0, 2, 4, 7, 9, 11, 12, 13, 14, 15, 16, 18, 19, 20}, {{1}, {2}, {2}, 
      {4}, {1}, {3}, {7}, {4}, {6}, {3}, {5}, {2}, {3}, {1}, {6}, {4}, {5}, 
      {6}, {7}, {7}}}, {-1, 1, -1, 1, 1, -1, -1, -1, 1, 1, -1, 1, -1, -1, 1, 
     1, 1, -1, -1, 1}}], "Species" -> 
   {enzyme[{"ID" -> "ANS", "Compartment" -> "c", "BoundCatalytic" -> {}, 
      "BoundActivators" -> {}, "BoundInhibitors" -> {}, 
      "CatalyticSites" -> Infinity, "ActivationSites" -> 0, 
      "InhibitionSites" -> 0}], enzyme[{"ID" -> "ANS", "Compartment" -> "c", 
      "BoundCatalytic" -> {Toolbox`Private`wrap[metabolite]["anth", "c"]}, 
      "BoundActivators" -> {}, "BoundInhibitors" -> {}, 
      "CatalyticSites" -> Infinity, "ActivationSites" -> 0, 
      "InhibitionSites" -> 0}], enzyme[{"ID" -> "ANS", "Compartment" -> "c", 
      "BoundCatalytic" -> {Toolbox`Private`wrap[metabolite]["gln_", "L"]}, 
      "BoundActivators" -> {}, "BoundInhibitors" -> {}, 
      "CatalyticSites" -> Infinity, "ActivationSites" -> 0, 
      "InhibitionSites" -> 0}], enzyme[{"ID" -> "ANS", "Compartment" -> "c", 
      "BoundCatalytic" -> {Toolbox`Private`wrap[metabolite]["anth", "c"], 
        Toolbox`Private`wrap[metabolite]["pyr", "c"]}, 
      "BoundActivators" -> {}, "BoundInhibitors" -> {}, 
      "CatalyticSites" -> Infinity, "ActivationSites" -> 0, 
      "InhibitionSites" -> 0}], enzyme[{"ID" -> "ANS", "Compartment" -> "c", 
      "BoundCatalytic" -> {Toolbox`Private`wrap[metabolite]["chor", "c"], 
        Toolbox`Private`wrap[metabolite]["gln_", "L"]}, 
      "BoundActivators" -> {}, "BoundInhibitors" -> {}, 
      "CatalyticSites" -> Infinity, "ActivationSites" -> 0, 
      "InhibitionSites" -> 0}], metabolite["anth", "c"], 
    metabolite["chor", "c"], metabolite["gln__L", "c"], 
    metabolite["glu__L", "c"], metabolite["pyr", "c"], 
    enzyme[{"ID" -> "ANS", "Compartment" -> "c", "BoundCatalytic" -> 
       {Toolbox`Private`wrap[metabolite]["anth", "c"], 
        Toolbox`Private`wrap[metabolite]["pyr", "c"], 
        Toolbox`Private`wrap[metabolite]["glu_", "L"]}, 
      "BoundActivators" -> {}, "BoundInhibitors" -> {}, 
      "CatalyticSites" -> Infinity, "ActivationSites" -> 0, 
      "InhibitionSites" -> 0}], metabolite["trp__L", "c"], 
    enzyme[{"ID" -> "ANS", "Compartment" -> "c", "BoundCatalytic" -> 
       {Toolbox`Private`wrap[metabolite]["gln_", "L"], 
        Toolbox`Private`wrap[metabolite]["trp__L", "c"]}, 
      "BoundActivators" -> {}, "BoundInhibitors" -> {}, 
      "CatalyticSites" -> Infinity, "ActivationSites" -> 0, 
      "InhibitionSites" -> 0}]}, "Fluxes" -> {v["ANS1"], v["ANS2"], 
    v["ANS3"], v["ANS4"], v["ANS5"], v["ANS6"], v["ANS_Kic_trp__L_1_chor"]}, 
  "ReversibleColumnIndices" -> {1, 2, 3, 4, 5, 6, 7}, "Pathway" -> {}}]
